### ISSUE TITLE
Not working (undefined is not an object)

### ISSUE THREAD

**Issue by yohanology** [APSL/react-native-keyboard-aware-scroll-view#10]
Hello,

I followed your instructions but when I focus on the text input I got an error:
`undefined is not an object (evaluating this.refs.scroll)`

Thanks

**Comment by alvaromb** [comment]
You forgot to add the `scroll` ref to your scroll component.

**Comment by yohanology** [comment]
actually I did.

But I used a solution found in previous issue and it's working:

`  _scrollToInput ( event, refName ) {
    let node = React.findNodeHandle( this.refs[ refName ] );
    let extraHeight = 70; // height of your text input 
    this.refs.scrollView.scrollToFocusedInput( event, node, extraHeight );
  }

  _scrollBack ( event, refName ) {
    let node = React.findNodeHandle( this.refs[ refName ] );
    let extraHeight = 0; // height of your text input 
    this.refs.scrollView.scrollToFocusedInput( event, node, extraHeight );
  }`

`      <KeyboardAwareScrollView
        ref='scrollView'
        contentContainerStyle={ styles.container }>
        <Image source={ require( '../resources/picto.png' ) } style={ styles.image }/>
        <Text style={ styles.title }>
          MULTIPASS
        </Text>
        <TextInput
          ref='email'
          style={ styles.input }
          placeholder="Email"
          autoCapitalize="none"
          autoCorrect={ false }
          onChangeText={ ( email ) => this.setState({ email }) }
          onFocus={ ( event ) => this._scrollToInput( event, 'email' ) }
          onBlur={ ( event ) => this._scrollBack( event, 'email' )}
          returnKeyType={ 'next'}
          clearButtonMode={ 'while-editing' }
          onSubmitEditing={ ( event ) => { 
            this.refs.password.focus(); 
          }}
        />`

Thanks for your package btw!

**Comment by alvaromb** [comment]
Cool!

Let me know if you need something else 👍
