### ISSUE TITLE
It is scrolling the background view as well while using with react-native-drawer

### ISSUE THREAD

**Issue by rohitgoyal** [APSL/react-native-keyboard-aware-scroll-view#100]
I am using react-native-drawer to make a drawer in my app. At the bottom of the drawer I have the TextInput component. Now this is working okay in iOS but in Android whenever the keyboard appears it scrolls the background view as well instead of just scrolling the drawer view. 

<img width="388" alt="screen shot 2017-02-10 at 12 19 13 am" src="https://cloud.githubusercontent.com/assets/4688513/22798069/a7533f54-ef26-11e6-8e5c-4f35ffbdbd2c.png">

<img width="388" alt="screen shot 2017-02-10 at 12 18 59 am" src="https://cloud.githubusercontent.com/assets/4688513/22798080/b139d960-ef26-11e6-9e3e-51ae48e4f5f1.png">

The background (blue one) component has also scrolled up. Anyone with any ideas?

**Comment by liu-jian-neu** [comment]
"Note that on Android performing text selection in input can change app's activity windowSoftInputMode param to adjustResize. This may cause issues with components that have position: 'absolute' while keyboard is active. To avoid this behavior either specify windowSoftInputMode in AndroidManifest.xml ( https://developer.android.com/guide/topics/manifest/activity-element.html ) or control this param programmatically with native code." from facebook.
Here u can set android:windowSoftInputMode="adjustNothing", and then listen the keyboardwillshow event and add the offset like implementation on IOS

**Comment by alvaromb** [comment]
Hi @rohitgoyal!

@liu-jian-neu suggestion seems right, because the Android auto scroll is performed by `windowSoftInputMode`.

**Comment by paalex** [comment]
Setting `android:windowSoftInputMode="adjustNothing"` prevents keyboardDidShow\keyboardWillShow from triggering..
