### ISSUE TITLE
ListView on iOS has default contentInset top=20.

### ISSUE THREAD

**Issue by guiherzog** [APSL/react-native-keyboard-aware-scroll-view#102]
Hi guys,
I'm trying to debug the library because of a weird **paddingTop** that my app is showing when using the **KeyboardAwareListView**. 
While I was able to discover that the `contentInset` has its default value with `top=20` while on the react native documentation a regular ListView has its `contentInset` `top=0`. 

Does someone can explain why ?

Thanks!

**Comment by serranoarevalo** [comment]
How did you fix this?

**Comment by guiherzog** [comment]
I set the `contentInset` prop to the following values=`{{top:0, bottom: 0, left:0, right:0}}`. The library is still setting its default to 20 though.

**Comment by serranoarevalo** [comment]
Cheers man.

**Comment by mu1ex** [comment]
This needs to be part of the document or should be fixed.

**Comment by alvaromb** [comment]
Hi @all!

The library is not setting any insets, it's RN that takes account of the height of the iOS status bar. If you feel this should be in the docs, please feel free to send a PR.

Another friendly reminder, I'm currently seeking for active contributors to the lib, please ping me if someone is interested.

**Comment by Swordsman-Inaction** [comment]
@alvaromb I'd like to maintain the library.

**Comment by superandrew213** [comment]
Setting `automaticallyAdjustContentInsets={false}` should fix this.
