### ISSUE TITLE
reactNode is null

### ISSUE THREAD

**Issue by tastycode** [APSL/react-native-keyboard-aware-scroll-view#11]
When following the instructions listed in the readme, on react-native 0.24, on iOS. I get the following message

![image](https://cloud.githubusercontent.com/assets/809953/15052047/3811715c-12c1-11e6-9288-e7124c8595b6.png)

I've traced it down to 

```javascript
_onTextFieldFocused(event, reactNode) {
   this.refs.scroll.scrollToFocusedInput(event, reactNode)
}
```

When I step into this function, after `onFocus={this._onTextFieldFocused}` is triggered. event is a `ReactSyntheticEvent` and `reactNode` is not defined. It seems that `scrollToFocusedInput` fails because no reactNode is present.

Any tips?

**Comment by alvaromb** [comment]
Hello @tastycode!

This is because you're sending a `null` node to the event. Try to debug what you're getting in the `findNodeHandle` function. Here you have a working example https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/8#issuecomment-210344833

Please ping me if you need anything else 😉

**Comment by alvaromb** [comment]
Hi @tastycode!

Please let me know if you need anything else and I'll reopen de issue.

**Comment by tastycode** [comment]
Thanks. Here is the code that ended up working.

```javascript
  _onNatureFocused = (event) {
    let reactNode = React.findNodeHandle(this.refs.natureField);
    this.refs.scroll.scrollToFocusedInput(event, reactNode);
  }

```

**Comment by alvaromb** [comment]
Glad to have helped @tastycode!

**Comment by alvaromb** [comment]
Once #22 gets merged, we'll no longer need to do this kind of stuff, the component will autoscroll to the focused `TextInput`.
