### ISSUE TITLE
scroll to cursor with a multiline textinput

### ISSUE THREAD

**Issue by reut-co** [APSL/react-native-keyboard-aware-scroll-view#113]
hey, i created a multiline textinput with a dynamic height - it fits itself to its content so it can grow dynamically. in that case I'm getting a situation that the textinput's height grows (when the user adds lines) and the cursor is hidden behind the keyboard.. what is the optimal solution for that case?

**Comment by alvaromb** [comment]
Try to play with the `extraScrollHeight` prop. You would need to know the size of the multiline input though.

**Comment by Palisand** [comment]
@reut-co Did you find a solution? I can scroll to the bottom of the input when it grows but I've spent all day trying and failing to scroll to the cursor when it is not at the end of the input's text.

**Comment by luco** [comment]
@alvaromb Working with `extraScrollHeight` doesn't work. Tips?

**Comment by Palisand** [comment]
@luco This isn't a problem with this project. I've tried to get this working for some time (using only Javascript), but it looks like there is no possible way to accomplishing scroll-to-cursor functionality without exposing the coordinates of the cursor, which RN does not do. You can get somewhat close, though, by using `onSelectionChange` to detect if the cursor is at the end of the text. If it isn't, then don't scroll to the input, but scroll down whenever the content size changes by the size change.

**Comment by luco** [comment]
@Palisand Do you have any example?

**Comment by Palisand** [comment]
Just threw this together but it should work provided your `scrollToInput` follows [this](https://github.com/APSL/react-native-keyboard-aware-scroll-view#programatically-scroll-to-any-textinput).

``` javascript
<TextInput 
  style={{height: this.state.height}}
  onChangeText={(text) => this.setState({text})}
  onSelectionChange={({nativeEvent}) => {
    this.setState({cursorPosition: nativeEvent.selection.start});
  }}
  onFocus={() => {
    if (this.state.cursorPosition === this.state.text.length) {
      this.scrollToInput();
    }
  }}
  onContentSizeChange={() => {
    this.setState({height}); 
    this.scrollToInput();
  }}
/>
```
Don't use inline arrow functions or styles of course.
You won't have to deal with expanding the height of the input when the content size changes on iOS if you use `minHeight`.

**Comment by baijunjie** [comment]
I've written a plugin that can solve multiple input problems
https://github.com/baijunjie/react-native-input-scroll-view

**Comment by Palisand** [comment]
I posted a [guide on medium](https://medium.com/@p9alisand/how-to-get-textinput-cursor-position-in-react-native-0-49-1845aee40e9b) on how to expose the cursor's position.

**Comment by baijunjie** [comment]
Hi @Palisand  I implemented this with pure javascript
https://github.com/baijunjie/react-native-input-scroll-view

**Comment by Palisand** [comment]
@baijunjie NICE! The only reason I have now for relying on the cursor's y coordinate is for a very specific case on Android. Can't wait until you add that functionality.
