### ISSUE TITLE
Android soft keyboard pushing up view

### ISSUE THREAD

**Issue by tmhoang1904** [APSL/react-native-keyboard-aware-scroll-view#114]
After app return from background, keyboard not pushing up view anymore.
Anyone has solution?

**Comment by Swordsman-Inaction** [comment]
The component doesn't support Android yet. 
But you can check if your `android:windowSoftInputMode` is set correctly in `AndroidManifest.xml` file.

**Comment by alvaromb** [comment]
Hi @tmhoang1904!

Which platform are you running? Can you show us some code snippet? Thanks.

**Comment by alvaromb** [comment]
I think this is more an upstream issue, because the component doesn't resize in Android.

**Comment by maulikvora** [comment]
@tmhoang1904 did you find any solution for it yet? we are facing same issue. text input is not pushing up when app return from background.
@alvaromb any suggestion to fix this or any alternative?

**Comment by alvaromb** [comment]
This is an upstream issue.
