### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by iRoachie** [APSL/react-native-keyboard-aware-scroll-view#116]
Hey! Great library mate. Are you interested in have typescript typings for this library? I've already started working on them since i'm using it in a couple of my react native projects using typescript. Let me know @alvaromb

**Comment by alvaromb** [comment]
Hi @iRoachie!

I use Flow, but I would love to have TS typing (AFAIK, they live in separate declaration files, right?). So I'm more than happy to merge a PR with that :)

**Comment by iRoachie** [comment]
Awesome! Will submit tonight

**Comment by iegik** [comment]
Flow errors:
```
node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareListView.js:37
 37:           this.props.onScroll && this.props.onScroll(e)
                                      ^^^^^^^^^^^^^^^^^^^^^^ call of method `onScroll`. Function cannot be called on
 37:           this.props.onScroll && this.props.onScroll(e)
                                      ^^^^^^^^^^^^^^^^^^^^^^ property `onScroll` of unknown type

node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareMixin.js:133
133:   handleOnScroll: function (e) {
                                 ^ parameter `e`. Missing annotation

```

**Comment by iRoachie** [comment]
@iegik open a new issue

**Comment by alvaromb** [comment]
@iegik yep! I would love to have a PR to solve those Flow errors.

**Comment by tibbus** [comment]
@iRoachie It would be nice to have typescript typings, I can contribute to it as well 👍

**Comment by iRoachie** [comment]
@tibbus I already finished them. The PR just needs to be merged. #118
