### ISSUE TITLE
addComponentAsRefTo error in RN0.44.0

### ISSUE THREAD

**Issue by georgest** [APSL/react-native-keyboard-aware-scroll-view#122]
![screen shot 2017-05-10 at 1 55 11 pm](https://cloud.githubusercontent.com/assets/3203859/25895403/62ae373e-3588-11e7-97ad-5e4a593d4977.png)

**Comment by alvaromb** [comment]
Can you post your source code?

**Comment by georgest** [comment]
```
<KeyboardAwareScrollView>
    <View>
        <Text>Test</Text>
    </View>
</KeyboardAwareScrollView>
```

I think the problem is in the mixin where you try to get the ref from another component, here:
```
getScrollResponder() {
    return this.refs._rnkasv_keyboardView.getScrollResponder()
}
```
Try installing React Native v0.44.0 and see if the error is shown.

I have fixed other of these error for refs like this:
`ref={(input) => { this.input = input; }}` and everything else is working fine.

**Comment by alvaromb** [comment]
Hi!

I'm running the component right now in a project with RN 0.44 and it's working perfectly.

**Comment by georgest** [comment]
What version of React you are running?

**Comment by alvaromb** [comment]
`"react": "16.0.0-alpha.6",`

**Comment by georgest** [comment]
Mine is the same.

So the error is somewhere else. I will research and try to fix it.

Thanks for your answer.
