### ISSUE TITLE
Typescript - missing typings

### ISSUE THREAD

**Issue by tibbus** [APSL/react-native-keyboard-aware-scroll-view#124]
Cannot pass `style` props using typescript:

` error TS2322: Type '{ style: { flex: number; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<KeyboardAwareScrollView> & Readonly<{ children?: R...'.
  Property 'style' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<KeyboardAwareScrollView> & Readonly<{ children?: R...'.`

[error](http://imgur.com/a/rMmTm)

PR open: [125](https://github.com/APSL/react-native-keyboard-aware-scroll-view/pull/125)

**Comment by tibbus** [comment]
I had the error because I was not using react-native @types

**Comment by tamdesktop** [comment]
Hi @tibbus, can you describe more detail about your fix?
