### ISSUE TITLE
0.2.9 broke our typescript project 

### ISSUE THREAD

**Issue by shrutic** [APSL/react-native-keyboard-aware-scroll-view#126]
> node_modules/react-native-keyboard-aware-scroll-view/index.d.ts(6,8): error TS1192: Module '"/@types/react/index"' has no default export.
> shared/components/CustomEventView.tsx(111,17): error TS2605: JSX element type 'KeyboardAwareScrollView' is not a constructor function for JSX elements.
>   Property 'render' is missing in type 'KeyboardAwareScrollView'.
> shared/components/CustomEventView.tsx(111,17): error TS2607: JSX element class does not support attributes because it does not have a 'props' property
> 
>  1 syntax error  2 non-emit-preventing type warnings

Upon upgrading to the latest keyboardawarescrollview, I get this error which is completely blocking our app continuous integration. For now, we will restrict ourselves to 0.2.8. Would appreciate if you could fix this issue.

**Comment by shrutic** [comment]
I believe you need to have an "export default" line at the end of your index.d.ts file similar to this one
https://github.com/Microsoft/react-native-code-push/blob/master/typings/react-native-code-push.d.ts

**Comment by tibbus** [comment]
What version of typescript are you using ? I use typescript **2.3.2** and don't have this issue.

**Comment by shrutic** [comment]
I am using 2.1.6

Shruti

**Comment by alvaromb** [comment]
Hi @shrutic !

How can I help you with this? I have no ts experience, can you send us a PR?
