### ISSUE TITLE
Integrate with react-native

### ISSUE THREAD

**Issue by stoffern** [APSL/react-native-keyboard-aware-scroll-view#130]
Why not integrate this with react-native it solves some critical issues with iOS problems.
ref: https://github.com/facebook/react-native/issues/8855

**Comment by alvaromb** [comment]
Already discussed in https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/56 and React Native repo.

**Comment by douglasjunior** [comment]
I got a good result using `android:windowSoftInputMode="adjustResize"` for Android and [IQKeyboardManager](https://github.com/hackiftekhar/IQKeyboardManager) for iOS.

I also created a [library](https://github.com/douglasjunior/react-native-keyboard-manager) for ease of use. 

Just install, no extra code needed:
```bash
npm install --save react-native-keyboard-manager
```

**Comment by stoffern** [comment]
I am talking about ios!

**Comment by douglasjunior** [comment]
Yes, my library is for Ios.

**Comment by stoffern** [comment]
@douglasjunior then create a PR to RN 😉

**Comment by douglasjunior** [comment]
The library has a different behavior. It uses the IQKeyboardManager.
