### ISSUE TITLE
Please update keyboardShouldPersistTaps in KeyboardAwareScrollView.js

### ISSUE THREAD

**Issue by gogosoon** [APSL/react-native-keyboard-aware-scroll-view#131]
As facebook have fixed the keyboard focus issue.

Add this param keyboardShouldPersistTaps='handled' prop to the ScrollView tag

**Comment by Swordsman-Inaction** [comment]
Sorry, I don't get it, why should we always use `handled`?

You can just pass the value through the props to `ScrollView` if you want to change the value.
