### ISSUE TITLE
Extra space above content

### ISSUE THREAD

**Issue by iRoachie** [APSL/react-native-keyboard-aware-scroll-view#136]
Using extraScrollHeight property leaves extra space when the keyboard is dismissed.

Is fixed by #121 

![Imgur](http://i.imgur.com/Y0O8MJt.gif)

**Comment by iRoachie** [comment]
At the top as well about 20px

**Comment by Adamnator92** [comment]
i facing the same issues too without `extraScrollHeight` apply

**Comment by Swordsman-Inaction** [comment]
`extraScrollHeight` will add extra space on the bottom is on purpose, use `extraHeight` property instead if you don't want this. @iRoachie 

About the extra space on top is an issue, I'm trying to figure it out. Might be a bug in `ScrollView`, but I'm not sure. Will let you know after I figure it out. @iRoachie @Adamnator92

**Comment by Swordsman-Inaction** [comment]
I've created a PR, you guys can check if it works. 😀

**Comment by iRoachie** [comment]
@Swordsman-Inaction Works great man, i've changed the title to reflect

**Comment by thomasbaldwin** [comment]
Any idea when this fix will be available through npm? Thanks!

**Comment by SupriyaKalghatgi** [comment]
Please reopen this issue

**Comment by alvaromb** [comment]
Have you tried to use `v0.3.0`? @Swordsman-Inaction AFAIK, this should be already merged and published!

**Comment by Swordsman-Inaction** [comment]
Yes, it's already merged

**Comment by cloudworkpro-hassen** [comment]
I am currently having this issue 😭
