### ISSUE TITLE
Warning: React.createClass and Warning: PropTypes

### ISSUE THREAD

**Issue by vlexaargas** [APSL/react-native-keyboard-aware-scroll-view#140]
I am seeing React.createClass and Warning: PropTypes error that look to be stemming from this library. Any plans to update soon?

<img width="797" alt="screen shot 2017-07-10 at 11 13 36 am" src="https://user-images.githubusercontent.com/6827692/28032844-de7146ba-6560-11e7-8141-bb5d7702aa3f.png">

**Comment by cladjules** [comment]
Hi there,

React.createClass has now been deleted from React Package in React 16.
React-native 0.46 is using it.

Do you plan to upgrade it using Extends instead?

thanks

**Comment by alvaromb** [comment]
Merged the new PR!

**Comment by aryo** [comment]
Any chance of an npmjs publish?

**Comment by Swordsman-Inaction** [comment]
@aryo Will release a new version after most PRs are merged. Won't be long.
