### ISSUE TITLE
Typescript Type errors

### ISSUE THREAD

**Issue by natalieweesh** [APSL/react-native-keyboard-aware-scroll-view#145]
```
Property 'onKeyboardWillShow' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<KeyboardAwareScrollView> & Readonly<{ children?: R...'.
```
```
Property 'scrollToPosition' does not exist on type 'ReactInstance'.
```

**Comment by alvaromb** [comment]
Hi @natalieweesh!

Can you help us solving these errors with a PR? I don't have any experience on TypeScript and I'm busy as hell ATM.

A PR would be very much appreciated, thanks!

**Comment by alvaromb** [comment]
I've changed some `*.ts` and Flow stuff here https://github.com/APSL/react-native-keyboard-aware-scroll-view/pull/173
