### ISSUE TITLE
Scroll not working when build configuration release

### ISSUE THREAD

**Issue by thanhtungdp** [APSL/react-native-keyboard-aware-scroll-view#15]
Hi, i have problem when build release.
But developer mode, it working well.
It not working, Can you check it.
I have test with other device like iphone 5, iphone 4s (it not working).
<img width="834" alt="screen shot 2016-05-12 at 9 30 13 pm" src="https://cloud.githubusercontent.com/assets/4653102/15218149/c6de4596-1888-11e6-8679-3deab08fc1f9.png">
<img width="808" alt="screen shot 2016-05-12 at 9 30 24 pm" src="https://cloud.githubusercontent.com/assets/4653102/15218150/c6dedda8-1888-11e6-9ea9-cf7e5938fd72.png">

**Comment by alvaromb** [comment]
Hello @thanhtungdp!

What's the build output?

**Comment by alvaromb** [comment]
Hey @thanhtungdp, I'm closing the issue. Please feel free to ping me if you need anything.
