### ISSUE TITLE
Scroll list back only when there is no content below to avoid blank space when keyboard goes away

### ISSUE THREAD

**Issue by chrisy-lili** [APSL/react-native-keyboard-aware-scroll-view#150]
I have a long list of questions, and I set `enableResetScrollToCoords={false}` to stop the view going back to the input that has the focus after I scroll to another question. But for the last question, it leaves blank space at the bottom :(   Is there a way to scroll the list back to prevent the blank space?

![untitled-1](https://user-images.githubusercontent.com/3959276/28732900-b03cac08-73a7-11e7-9099-df2c6bf67e21.jpg)

**Comment by Swordsman-Inaction** [comment]
That's what `enableResetScrollToCoords={false} ` does. If there is no blank space at the bottom, the whole view will scroll to the end. But you set `enableResetScrollToCoords={false}` to stop the view going back, right?

@chrisy-lili Is my understanding right?

**Comment by zer0nim** [comment]
I know it's an old issue but I had the same problem today, I finally managed to handle it, so if it can help someone.

I proceeded this way:
```
...

state = {
    overflow: false
}

// Check if there is overflow
overflowBottom(nativeEvent) {
    const { layoutMeasurement, contentOffset, contentSize } = nativeEvent
    return layoutMeasurement.height + contentOffset.y > contentSize.height
}

render() {
    return (
        <KeyboardAwareScrollView
            ref={view => {
                this.view = view
            }}
            onKeyboardWillHide={() => {
                if (this.state.overflow) {
                    // After closing keyboard, scrollToEnd if there is overflow
                    this.view.scrollToEnd()
                }
            }}
            onMomentumScrollEnd={(event) => {
                // At the end of scroll save the overflow status to the state
                this.setState({ overflow: this.overflowBottom(event.nativeEvent) })
            }}
            enableResetScrollToCoords={false}
        >
    )
}

...
```
