### ISSUE TITLE
Text selection on ScrollView

### ISSUE THREAD

**Issue by yogevlahyani** [APSL/react-native-keyboard-aware-scroll-view#151]
Hello, This package is perfect for me, but I didn't manage to make a text selection on my TextInput.
I understood that theres a bug when on ScrollView and I have searched here for issues or PR's and didn't find a thing.

The most important thing for me right now is the "Paste" option and I can make that by making a longPress event, but that's not what i'm looking for ..

Any solutions ?

**Comment by alvaromb** [comment]
Seems more an upstream issue, can you set up a code snippet to try to reproduce the issue?
