### ISSUE TITLE
support for "keyboardShouldPersistTaps" as ScrollView does

### ISSUE THREAD

**Issue by shikherprasad** [APSL/react-native-keyboard-aware-scroll-view#157]
When keyboard is open, touchables doesn't work on single tap. On first tap, keyboard gets closed, and then touchables work. Touchables should also work when keyboard is open.

**Comment by chrise86** [comment]
@shikherprasad why did you close this? Setting `keyboardShouldPersistTaps='always'` does not seem to work for me 😕

**Comment by jsuryahyd** [comment]
The Link to the comment helped. For me, it was a `Flatlist` inside the `KeyboardAwareScrollView`, I set the `keyboardShouldPersistTaps` on the flatlist too, and it worked.
