### ISSUE TITLE
What is the point of viewIsInsideTabBar property of KeyboardAwareMixin?

### ISSUE THREAD

**Issue by Palisand** [APSL/react-native-keyboard-aware-scroll-view#158]
I do not understand the purpose of [this](https://github.com/APSL/react-native-keyboard-aware-scroll-view/blob/master/lib/KeyboardAwareMixin.js#L44) since the `viewIsInsideTabBar` **property** is [set](https://github.com/APSL/react-native-keyboard-aware-scroll-view/blob/master/lib/KeyboardAwareMixin.js#L32) but never used again (only the **prop** is used).

**Comment by Swordsman-Inaction** [comment]
I think you are right, `this.viewIsInsideTabBar ` is useless, we are just using the prop one.

**Comment by Palisand** [comment]
Thanks
