### ISSUE TITLE
Setting scrollEventThrottle to 0 results in wrong automatic resetScrollToCoords

### ISSUE THREAD

**Issue by luqiuyuan** [APSL/react-native-keyboard-aware-scroll-view#159]
According to React Native Docs, value 0 of scrollEventThrottle "results in the scroll event being sent only once each time the view is scrolled". Setting it to 0 leads wrong automatic resetScrollToCoords.

![2017-08-24 23_56_09](https://user-images.githubusercontent.com/27582026/29699057-d73ccf00-8927-11e7-836f-c5fe72ef7065.gif)

**Comment by alvaromb** [comment]
Thanks for reporting @luqiuyuan!

Would you be happy sending us a PR? 😺

**Comment by luqiuyuan** [comment]
Hello @alvaromb I have submitted a pull request #161

**Comment by alvaromb** [comment]
@luqiuyuan merged, will release today!
