### ISSUE TITLE
when I apply the component it results scrolls up a little ? 

### ISSUE THREAD

**Issue by a-eid** [APSL/react-native-keyboard-aware-scroll-view#160]
![](https://i.imgur.com/HSOV024.png) before applyying it 

![](https://i.imgur.com/YkCFE77.png) after applying it 

I'm using android , testing on a real device , using latest react-native 47 , and expo

**Comment by Swordsman-Inaction** [comment]
@a-eid Cannot reproduce it, could you please provide a code snippet to reproduce it? Also which version are you using?

**Comment by alvaromb** [comment]
Hi @a-eid!

Please provide more info to re-open the issue.

Thanks!

**Comment by a-eid** [comment]
@alvaromb I have abandoned the project I was working on , if I reproduce the problem I will make sure to include a code snippet to reproduce the problem .
