### ISSUE TITLE
KeyboardAwareFlatList is not exposed

### ISSUE THREAD

**Issue by iddan** [APSL/react-native-keyboard-aware-scroll-view#163]
Can only be imported from `react-native-keyboard-aware-scroll-view/lib/KeyboardAwareFlatList`

**Comment by mr746866** [comment]
Is this issue fixed in latest release?

**Comment by alvaromb** [comment]
@mr746866 yes

**Comment by jhalborg** [comment]
Does not seem to be inlcuded in the TypeScript definition yet, or am I doing something wrong?

**Comment by jhalborg** [comment]
Tagging @alvaromb - And while I'm at it, thanks for a great lib! ;)
