### ISSUE TITLE
0.26 breaking change

### ISSUE THREAD

**Issue by anthonywebb** [APSL/react-native-keyboard-aware-scroll-view#17]
Looks like RN 0.26 broke this plugin, the error I get is
"Super expression must either be null or a function, not undefined"

**Comment by anthonywebb** [comment]
Forgot to mention, I was testing the latest react-native-keyboard-aware-view@0.0.8

**Comment by alvaromb** [comment]
Thanks for reporting @anthonywebb!

Will update the component as soon as I can.

**Comment by anthonywebb** [comment]
@alvaromb thanks so much for a great component!

**Comment by alvaromb** [comment]
I'll update the component tomorrow. Thanks for your patience @anthonywebb 😉

**Comment by alvaromb** [comment]
Hello @anthonywebb.

Just tested 0.0.8 with 0.26.1 and it's working great. Please check your app code, here you have more info: https://github.com/facebook/react-native/issues/7711.
