### ISSUE TITLE
PropsType is no longer within React package in the latest update

### ISSUE THREAD

**Issue by BBXiong** [APSL/react-native-keyboard-aware-scroll-view#171]
As per latest update, PropsType is no longer within 'react', but exist in its own 'props-type' package.
Read here for more info:
https://facebook.github.io/react/docs/typechecking-with-proptypes.html

Also, I notice that React.CreateClass no longer work with the latest react native, and you would need to use the 'export default class XXX extends Component {' way of exporting the class.

**Comment by alvaromb** [comment]
I'm working on this, thanks for your issue!

**Comment by alvaromb** [comment]
There's a big library change coming, please take a look here https://github.com/APSL/react-native-keyboard-aware-scroll-view/pull/173

I would like to have some feedback from you before releasing.
