### ISSUE TITLE
Support iPhone X

### ISSUE THREAD

**Issue by TimoGlastra** [APSL/react-native-keyboard-aware-scroll-view#177]
The height of the tabbar for iOS is set to 49 but the height of the tabbar is higher on the iPhone X (I believe it is 83?). So now there is extra whitespace on the bottom of the scrollview. I think it will be easy to fix this with detecting an iPhone X and setting the tabbar height based on that.

**Comment by alvaromb** [comment]
Merged #178, will release today.
