### ISSUE TITLE
Argument 0 (NSNumber) of RCTUIManager.measureLayout must not be null

### ISSUE THREAD

**Issue by tonyxiao** [APSL/react-native-keyboard-aware-scroll-view#18]
Getting this error. Any ideas?

![image](https://cloud.githubusercontent.com/assets/696842/15442826/74e532ac-1e98-11e6-9acb-e0861d731959.png)

Src
```javascript
class ScrollableLoginScreen extends React.Component {
  _scrollToInput (event, reactNode) {
  // Add a 'scroll' ref to your ScrollView
    this.refs.scroll.scrollToFocusedInput(event, reactNode)
  }
  
  render() {
    return (
      <KeyboardAwareScrollView ref='scroll'>
        <LoginScreen {...this.props} scrollToInput={this._scrollToInput.bind(this)} />
      </KeyboardAwareScrollView>
    )
  }
}
class LoginScreen extends React.Component {
  render() {
    const {fields, handleSubmit, submitting, error, scrollToInput, ...props} = this.props
    return (
      <View style={styles.screen}>
        <StatusBar hidden={false} />
        <View style={styles.modal}>
          <IconTextInput ref='my-input' iconName="envelope-o" placeholder='Email' style={styles.input} {...fields.email} onFocus={scrollToInput} />
          <IconTextInput iconName="lock" placeholder='Password' style={styles.input} {...fields.password} onFocus={scrollToInput} />
          <Button style={theme.BUTTON} styleDisabled={theme.BUTTON_DISABLED} containerStyle={styles.loginButton} 
            disabled={submitting} onPress={handleSubmit}>LOGIN</Button>
          {submitting && <Spinner />}
          {(!submitting && error) && <Text style={theme.TEXT_ERROR}>{error}</Text>}
        </View>
      </View>
    )
  }
}
```

**Comment by grsabreu** [comment]
![selection_019](https://cloud.githubusercontent.com/assets/1283200/15445778/19b3714c-1edd-11e6-81fc-51c57c8cd919.png)
I'm also having something like that running in a real device

**Comment by alvaromb** [comment]
The error is due to React being unable to find the node because findNodeHandle doesn't get a React node as a parameter. 

If you're using RN 0.26 keep in mind that it's still not supported yet. The code must be changed from React.findNodeHandle to ReactNative.findNodeHandle. 

Sorry, will release a compatible version on Monday. 

Enviado desde mi iPhone

**Comment by marcosinigaglia** [comment]
I have the same issue using RN 0.25.1

**Comment by alvaromb** [comment]
@marcosinigaglia my comment is valid for RN>=0.25.

**Comment by adamrainsby** [comment]
@alvaromb I seem to be having the same issue on 0.24.0

**Comment by alvaromb** [comment]
Hello!

Please debug the `scrollToFocusedInput` method. Try to `console.log(event, reactNode)` because that error usually appears then `reactNode` is `null`.

**Comment by adamrainsby** [comment]
@alvaromb Yeah that was the problem for me. Thanks

**Comment by dnish** [comment]
Are there any updates on this? I'm having the same issue on 0.25.1

**Comment by alvaromb** [comment]
@dnish there's no update. This errors appears when the `reactNode` sent to the `scrollToFocusedInput` is null. Please post your code if you need further help. Closing this issue.

**Comment by alvaromb** [comment]
Hi everybody!

Once #22 gets merged, we'll no longer need to do this kind of stuff, the component will autoscroll to the focused `TextInput`.

**Comment by grsabreu** [comment]
Thanks man, that feature is really sweet. Things got working here.
