### ISSUE TITLE
After upgrade: ambiguous resolution: module

### ISSUE THREAD

**Issue by mschipperheyn** [APSL/react-native-keyboard-aware-scroll-view#181]
RN 0.49.3
```
error: bundling failed: ambiguous resolution: module `/react/projects/ology_mobile_templates/Ology/index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/react/projects/ology_mobile_templates/Ology/node_modules/react-native-drawer-layout-polyfill/node_modules/react-native/package.json`
  * `/react/projects/ology_mobile_templates/Ology/node_modules/react-native-drawer-layout/node_modules/react-native/package.json`
  * `/react/projects/ology_mobile_templates/Ology/node_modules/react-native-iphone-x-helper/node_modules/react-native/package.json`
  * `/react/projects/ology_mobile_templates/Ology/node_modules/react-native-keyboard-aware-scroll-view/node_modules/react-native/package.json`
  * `/react/projects/ology_mobile_templates/Ology/node_modules/react-native-tab-view/node_modules/react-native/package.json`
  * `/react/projects/ology_mobile_templates/Ology/node_modules/react-native/package.json`
```

**Comment by alvaromb** [comment]
Can you update to `0.4.1`?

**Comment by mschipperheyn** [comment]
Hmm, weirdly enough the error remains. Did a clean of tmpdir, watchman, build folder and node_modules and verifies that react-native is now a peer dependency for `react-native-keyboard-aware-scroll-view` but I keep getting the error. Hmmm, odd.

**Comment by alvaromb** [comment]
Which RN version are you working on?

**Comment by mschipperheyn** [comment]
0.49.3

**Comment by mschipperheyn** [comment]
I also see that react-native is no longer present in the react-native-keyboard-aware-scroll-view/node_modules folder.

**Comment by mschipperheyn** [comment]
Cache cleaned again. Also did a hard reset on the simulator now. Still have the problem.

**Comment by mschipperheyn** [comment]
Not sure what it could be. This `node_modules/bin/react-native` looks odd.

<img width="326" alt="screen shot 2017-10-24 at 11 26 42" src="https://user-images.githubusercontent.com/384959/31945577-5fd4d6e0-b8ae-11e7-86ec-3f5927abcf6b.png">

**Comment by alvaromb** [comment]
Can't reproduce the issue with a 0.49.3 RN project and a 0.4.1 `react-native-keyboard-aware-scroll-view` 😢

**Comment by mschipperheyn** [comment]
I think some kind of link was created between the app dir and the Trash after removing node_modules. Cleaning trash, cleaning cache again, restart solved the issue.

**Comment by alvaromb** [comment]
Cool! glad to hear!

**Comment by redeemedfadi** [comment]
I had to run `react-native start --reset-cache` after accidentally installing 0.4.0.
