### ISSUE TITLE
Working for floating numeric keyboards?

### ISSUE THREAD

**Issue by jeaye** [APSL/react-native-keyboard-aware-scroll-view#183]
Hey there, is there meant to be support for the floating numeric keyboards that Samsung tablets, and other tablets have? Here's an example of what it looks like: https://stackoverflow.com/questions/40887395/android-the-numeric-floating-keyboard-blocks-edittext-on-10-inch-tablet

I haven't seen a solution for ensuring these floating keyboards don't obscure the text input and I don't see any specific mention of support for these types of keyboards in the docs or source for this repo.

Thanks!

**Comment by alvaromb** [comment]
We won't be supporting these keyboards due to a high amount of work we have ATM, but I would gladly review, merge and release a new version if you want to send us a PR :)

**Comment by jeaye** [comment]
Ok, great to know officially whether or not these are supported. Thanks for the response. I'm not yet sure of the approach we're going to be taking, either a custom keyboard, tolerating with the floating keyboards on certain devices, or implementing a solution using avoidance.

We can leave this open with a Help Wanted tag, or do whatever you like with it. If my team ends up implementing this, I'll drop a note so you'll know it's being worked on.

**Comment by alvaromb** [comment]
Done!

Unfortunately, we don't have the time to implement this, but feel free to ping me if you need a hand bringing support to this type of keyboard.
