### ISSUE TITLE
Animated Scrollview

### ISSUE THREAD

**Issue by Aleksandar-FFWD** [APSL/react-native-keyboard-aware-scroll-view#184]
I was wondering is there a way to implement the keyboard logic using this module into Animated.ScrollView component.. I have some things animated based on scroll position (like header resizing, color darkening, etc. ) that I would like to keep along with implementation of scroll to input on iOS.

Appreciate the feedback :)

**Comment by alvaromb** [comment]
Sure @Aleksandar-FFWD!

The latest implementation of the library consists of a High Order Component, you can generate a keyboard-aware-`Animated.ScrollView` like this:

```js
import { Animated } from 'react-native'
import { listenToKeyboardEvents } from 'react-native-keyboard-aware-scroll-view'

export default listenToKeyboardEvents(Animated.ScrollView)
```

**Comment by Aleksandar-FFWD** [comment]
@alvaromb that works when you'r using a regular Component, however when using an `Animated.ScrollView`  it does not work.

The reason behind that is that the `ref` of the Scroll component in the `Animated.ScrollView` is located in `ref._component` prop.

I didn't notice there is a way to suggest a `ref` of the component to `listenToKeyboardEvents` so a workaround I suggest is adding the following:

```
_handleRef = (ref: React.Component<*>) => {
   this._rnkasv_keyboardView = ref;

   //I'm just going to leave this here
   if (ref && ref._component) {
      this._rnkasv_keyboardView = ref._component;
   };

   if (this.props.innerRef) {
      this.props.innerRef(this._rnkasv_keyboardView)
   }
}
```

**Comment by zgordon02** [comment]
I know this is a 6 year old comment, but can you provide more detail on your solution here @Aleksandar-FFWD ?

I would like to use this with reanimated's `Animated.ScrollView` and am running into the same issue, but cannot understand the context around your code snippet. Is that to be patched somewhere in this lib or is that your code?
