### ISSUE TITLE
It do not work when used in webview 

### ISSUE THREAD

**Issue by aheadlcx** [APSL/react-native-keyboard-aware-scroll-view#185]
When used in webview , this do not work well on Android .Can you solve is ?

**Comment by AbdallaMohamed** [comment]
Just out of curiosity, how could you be using that component in webview?

**Comment by alvaromb** [comment]
This component is not intended to be used in a `WebView`. You can adjust the size of the `WebView` when the keyboard pops up, but you'll be unable to scroll to a specific input.
