### ISSUE TITLE
iOS Simulator crashes when setting state after Promise resolves

### ISSUE THREAD

**Issue by lucastobrazil** [APSL/react-native-keyboard-aware-scroll-view#188]
Just upgraded from 0.2.9 to 0.4.1 and iOS simulator is crashing when calling setState after this promise resolves... 

Crash doesnt happen when calling setState outside of the  promise 

Using Expo 22.0.1 and associated react native dependencies.
```
export default class EntityCommentView extends Component {
    constructor(props) {
        super(props);
        this.state = {
            comments: null,
        };
    }
    doGetComments() {
        // Works fine
        this.setState({ comments: [] });
        return getComments().then(res => {
            // iOS Simulator Crashes here
            this.setState({ comments: res });
        });
    }
    componentDidMount() {
        return {
            comments: this.doGetComments(),
        };
    }
    render() {
        const { navigation } = this.props;
        const { comments } = this.state;

        return (
            <KeyboardAwareScrollView
                navigation={navigation}
                extraHeight={85}
                contentContainerStyle={{
                    flex: 1,
                    flexDirection: 'column',
                }}
                keyboardShouldPersistTaps="always"
            >
                <ScrollView style={{ flex: 1 }} ref={input => (this.inputRefs.scrollView = input)}>
                    ...stuff
                </ScrollView>
                <PostCommentContainer>
                    <CommentInput  />
                </PostCommentContainer>
            </KeyboardAwareScrollView>
        );
    }
}
```

**Comment by alvaromb** [comment]
Hello @lucastobrazil !!

This error doesn't seem to be related to the library, can you send us a stacktrace or a more detailed error message?

**Comment by lucastobrazil** [comment]
@alvaromb sure thing, i'll look a bit deeper however there's nothing getting shown in the Expo logs so ill see if there's any way of getting a more detailed stacktrace

**Comment by lucastobrazil** [comment]
@alvaromb i've still not been able to get any clear stacktrace on the error. But i can confirm that when I simply `setState` with hardcoded array data, it's fine. Something seems to be going wrong in the promise.

I've tried:

`this.setState({data: [ myArray ]});`
^^ works fine.

But then, with the same hardcoded array data
```
return apiPromiseCall().then(res => {
    this.setState({data: [ myArray ]});
});
```

^^ crashes.

**Comment by alvaromb** [comment]
Sorry @lucastobrazil, this seems that it's not a problem with the library. Please post the question to StackOverflow, where you will find better support.

**Comment by lucastobrazil** [comment]
@alvaromb oh right? I'm sorry i couldn't get any further details to you, but not sure if that warrants it being closed? The issue only happens with this library, under the above conditions. 

But sure I'll ask around then. Maybe others might find similar issues. Will report back if I discover where the problem lay.
