### ISSUE TITLE
How to set `windowSoftInputMode` with Expo Apps?

### ISSUE THREAD

**Issue by lucastobrazil** [APSL/react-native-keyboard-aware-scroll-view#190]
> First, Android natively has this feature, you can easily enable it by setting windowSoftInputMode in AndroidManifest.xml. 

Just a question about this - is there a way to set this for apps using Expo CRNA? they have an `app.json` file which i _think_ relates to setting app-wide settings, but unsure how to set this property specifically.

Love this plugin, it's super nice to work with, so thanks! :)

**Comment by Swordsman-Inaction** [comment]
From the [official doc](https://docs.expo.io/versions/latest/introduction/faq.html#how-do-i-add-custom-native-code-to-my-expo-project)

`Standard Expo projects don’t support custom native code, including third-party libraries which require custom native components. In an Expo project, you only write pure JS. Expo is designed this way on purpose and we think it’s better this way.`

Sorry, I don't use `Expo`, maybe you can get more help in [Expo Repo](https://github.com/expo/expo/issues)
