### ISSUE TITLE
KeyboardAwareScrollView stopping event from propagating on android only.

### ISSUE THREAD

**Issue by Spoof14** [APSL/react-native-keyboard-aware-scroll-view#191]
I have a minor problem with not being able to focus a TextInput or a button, when a TextInput is already focused. I believe the view is taking the event meant for the other components and stopping propagation. 
Behaviour on iOS: 
Click TextInput -> keyboard shows -> Click another TextInput -> keyboard stays and the other Text input is now focused.   
This is the behaviour i want, but on Android it is:
Click TextInput -> keyboard shows -> Click another TextInput -> keyboard hides TextInput loses focus -> click another TextInput again -> keyboard shows and the TextInput is focused.

Does anyone have a fix for this, or is this just the way it is on android?

**Comment by alvaromb** [comment]
I think you should play with the `ScrollView` props, this is due to either `softInputMode` or http://facebook.github.io/react-native/releases/next/docs/scrollview.html#keyboardshouldpersisttaps

**Comment by Spoof14** [comment]
Thanks! I fixed it with the keyboardShouldPersistTaps='handled'
