### ISSUE TITLE
I got an error PropTypes.bol is undefined

### ISSUE THREAD

**Issue by mongveasna** [APSL/react-native-keyboard-aware-scroll-view#192]
undefined is not an object  (evaluating '_react.PropTypes.bool')

<unknown>
 keyboardAwareMixin.js:16:41
LoadModuleImplemenation
require.js:192.12

my react native verion
react-native-cli: 2.0.1
react-native: 0.50.1

**Comment by alvaromb** [comment]
Please update to the latest version of the library :)
