### ISSUE TITLE
Disable animations when scrolling programmatically

### ISSUE THREAD

**Issue by Waltari10** [APSL/react-native-keyboard-aware-scroll-view#194]
Hey,

I am using the "scrollToFocusedInput" function and it is working great. When triggered it slowly scrolls/animates to the textInput. Is there anyway to make it instant though? So that it would just teleport the scrollview position to the input. 

Thanks!

**Comment by alvaromb** [comment]
Hello @Waltari10!

Right now it's not configurable, so you will always get the animation. How do you feel about sending a PR for this?

Here's the important part, we could use a `prop` to configure this: https://github.com/APSL/react-native-keyboard-aware-scroll-view/blob/master/lib/KeyboardAwareHOC.js#L138

**Comment by Waltari10** [comment]
Hey, good idea. If we end up implementing this I'll make sure to make a PR.

**Comment by luco** [comment]
This would be awesome.
