### ISSUE TITLE
Possible to force dismiss keyboard?

### ISSUE THREAD

**Issue by btroia** [APSL/react-native-keyboard-aware-scroll-view#196]
Hi, is it possible to force dismiss the keyboard? For example, I would like pressing the "done" keyboard button to force the keyboard to close without the user having to press outside of the input area. Thanks!

**Comment by janmarsicek** [comment]
@btroia can't you use `dismiss` method from RN Keyboard? http://facebook.github.io/react-native/releases/next/docs/keyboard.html#dismiss

Also there is a package for this https://www.npmjs.com/package/react-native-dismiss-keyboard but it is deprecated as the feature was already implemented to the core.

**Comment by btroia** [comment]
@janmarsicek yes, this requires including the RN `Keyboard` library and calling `Keyboard.dismiss()` instead of `react-native-keyboard-aware-scroll-view` simply exposing it.

**Comment by janmarsicek** [comment]
@btroia and is this a problem?

BTW it works for me out of the box if I press Enter button (or whatever the text on the button is) keyboard disappears, also check `blurOnSubmit` prop

**Comment by btroia** [comment]
@janmarsicek no, not a problem. Just for convenience 😁  because otherwise it requires having to import `Keyboard` from react-native just to access `Keboard.dismiss()` when otherwise I don't need to import it.

**Comment by alvaromb** [comment]
The right way to do it is to import `Keyboard` from `react-native`. This library should not obscure it if it's provided through RN, IMHO.
