### ISSUE TITLE
Bug on RN>=0.49

### ISSUE THREAD

**Issue by snksergio** [APSL/react-native-keyboard-aware-scroll-view#198]
Hello, when i focus on input in KeyboardAwareScrollView then I will focus another input, my keyboard dismiss and input don't receive focus...  on RN>=0.49

![bug](https://user-images.githubusercontent.com/8795684/33028757-e1218e82-cdfd-11e7-965b-49559093bdbb.png)

**Comment by Waltari10** [comment]
I have a similar problem. Except when I have a textInput focused inside a KeyboardAwareScrollView and I press a button the button doesn't do anything...

**Comment by Waltari10** [comment]
Try this:

```
 <KeyboardAwareScrollView
    keyboardShouldPersistTaps='always'
 >
```

**Comment by snksergio** [comment]
@Waltari10 thanks man!!! 💯
