### ISSUE TITLE
setState/rerender causes scrollview to break

### ISSUE THREAD

**Issue by robinclaes** [APSL/react-native-keyboard-aware-scroll-view#199]
I have a KeyboardAwareScrollView with controlled TextInput fields. Each TextInput has an onChange method that sets the state with .setState()

Whenever I type text and try to scroll with my finger, the ScrollView seems to reset, disabling scrolling, putting my content behind the keyboard (like a regular view).

More people with this issue?

**Comment by vysotsky** [comment]
The same issues which appears in case I re-render some views by changing state

**Comment by robinclaes** [comment]
@vysotsky Android doesn't seem to work properly with 0.3.0 and RN 0.49.3

Does it work for you?

**Comment by alvaromb** [comment]
https://github.com/APSL/react-native-keyboard-aware-scroll-view/blob/master/lib/KeyboardAwareHOC.js#L348
