### ISSUE TITLE
Working with View + ScrollView

### ISSUE THREAD

**Issue by dnish** [APSL/react-native-keyboard-aware-scroll-view#20]
Hey,
here is my code related to https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/18#issuecomment-222483127

I'm using the following structure

video.js

    Posting extends from React.Component {

      constructor(props) {
        super(props);
    }

    _scrollToInput (event, reactNode) {
     this.refs.scroll.scrollToFocusedInput(event, reactNode)
    }

    render() {
      return 
        (<View>
         <Video/>
          <KeyboardAwareScrollView ref='scroll'>
            <CommentItem/>
            <CommentItem/>
            <TextInput onFocus={this._scrollToInput}/>
         </KeyboardAwareScrollView>
        </View>)
     }

    }

If I click on the text input, <code>reactNode</code> is null. I'm using RN 0.25.1

**Comment by alvaromb** [comment]
Try this `this._scrollToInput.bind(this)`.

**Comment by alvaromb** [comment]
@dnish once #22 gets merged, we'll have automatic scroll when `TextInput` gets focused.

**Comment by alvaromb** [comment]
Merged #22
