### ISSUE TITLE
Support for Animated.event

### ISSUE THREAD

**Issue by jhalborg** [APSL/react-native-keyboard-aware-scroll-view#200]
Hey! 

Thanks for a great lib. 

Any way to add an onScroll Animated.event to the component for some cool animation shenanigans? :)

Would be awesome if one could do something along the lines of

```
<KeyboardAwareScrollView
        style={styles.container}
        onScroll={Animated.event(
          [{ nativeEvent: { contentOffset: { y: this.state.scrollY } } }],
          { useNativeDriver: true }
        )}
      >
    <View />
</KeyboardAwareScrollView>
```

**Comment by alvaromb** [comment]
Hello @jhalborg!

This can actually be done, please check https://github.com/APSL/react-native-keyboard-aware-scroll-view/blob/master/lib/KeyboardAwareHOC.js#L348

**Comment by jhalborg** [comment]
Cool, thanks! It works! :-)

For anyone coming across this issue, remember to make the component animated using `Animated.createAnimatedComponent`, otherwise it will not work. Something like:

```
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';
...
const AnimatedKeyboardAwareScrollView = Animated.createAnimatedComponent(
  KeyboardAwareScrollView
);
...
const scale = this.state.scrollY.interpolate({
      inputRange: [-180, 0],
      outputRange: [0.5, 1],
      extrapolate: 'clamp',
    });

    return (
      <AnimatedKeyboardAwareScrollView
        scrollEventThrottle={16}
        onScroll={Animated.event(
          [{ nativeEvent: { contentOffset: { y: this.state.scrollY } } }],
          { useNativeDriver: true }
        )}
      >...</AnimatedKeyboardAwareScrollView>
```

**Comment by Aleksandar-FFWD** [comment]
@alvaromb No it cant, It crashes. When setting: 
```
    onScroll={
        Animated.event(
            [{ nativeEvent: { contentOffset: { y: this.state.scrollY } } }],
            { useNativeDriver: true },
        )
    }
```
The reason is, `this.props.onScroll` is not a function, it's an object if you pass `{ useNativeDriver: true }`.
First, it brakes `propTypes` because it's expecting a function and not an object.
And second, it crashes when you try to scroll because he calls `this.props.onScroll` as a function.

I'we been messing arround `_onScroll` function but could not figure out what I need to pass. 

```
    _onScroll = (
      e: SyntheticEvent<*> & { nativeEvent: { contentOffset: number } }
    ) => {
      this._handleOnScroll(e)

      // `unseNativeDrivers = false
      if (typeof this.props.onScroll === 'function') {
        return this.props.onScroll(e);
      };

      // When `unseNativeDrivers
      if (typeof this.props.onScroll === 'object' && this.props.onScroll.__isNative) {
        //Figure out what we need to pass onScroll
      };
    }
```

**Comment by jhalborg** [comment]
@Aleksandar-FFWD - I ran into the same problem, but found the solution to be using 

```
const AnimatedKeyboardAwareScrollView = Animated.createAnimatedComponent(
  KeyboardAwareScrollView
);
```
as noted above. The reason being that this provides the view with the `Animated` onScroll event that takes a declarative Animation object. You can read more [here](https://facebook.github.io/react-native/docs/animations.html#animated-api)

**Comment by Aleksandar-FFWD** [comment]
@jhalborg It's still keyboard aware I guess ?

**Comment by jhalborg** [comment]
Yes :)

**Comment by Aleksandar-FFWD** [comment]
@jhalborg Grate! Thanks. I was banging my head for 2 days to try and figure out how to make it work. On my way to test it! 👍

**Comment by Aleksandar-FFWD** [comment]
@jhalborg Doesent work for me when `{ useNativeDriver: true }`

**Comment by jhalborg** [comment]
Don't know what to tell you, friend. It works for me with the code I've provided above. 

Using Expo 24/React Native 0.51 and version 0.4.1 of this lib. Good luck :)

**Comment by alvaromb** [comment]
@Aleksandar-FFWD do you have a repro for the issue you're experiencing that can be pasted & formatted here?

**Comment by SebiVPS** [comment]
I have the same issue.
I use:
```
const AnimatedKeyboardAwareScrollView = Animated.createAnimatedComponent(
  KeyboardAwareScrollView
);
```
It works fine on iOS. On Android as soon as `refreshControl` is used, it stops working.

**Comment by ddxxtony** [comment]
In my case if I use this { useNativeDriver: true }, it stops working

**Comment by marquina-abreu** [comment]
@SebiVPS this happens to me too
