### ISSUE TITLE
Content is collapsed when a TextInput is focused in KeyboardAwareScrollView container on Android

### ISSUE THREAD

**Issue by anisa07** [APSL/react-native-keyboard-aware-scroll-view#203]
Android 6.0

**Comment by rynatk** [comment]
@anisa07 since no explanation was left, and your description was the best articulation of the problem I was just facing, my solution wound up being:

`enableAutomaticScroll={(Platform.OS === 'ios')}`

That prop was making everything collapse instead of _pan_ on Android.
