### ISSUE TITLE
React Navigation StackNavigator on Android

### ISSUE THREAD

**Issue by MR03web** [APSL/react-native-keyboard-aware-scroll-view#206]
Set windowSoftInputMode to adjustPan in AndroidManifest.xml.
Set enableOnAndroid property to true.

result:
![screenshot_2017-12-15-18-20-19-762_com textinput](https://user-images.githubusercontent.com/34115164/34037898-61c123c4-e1c5-11e7-8eda-e80044db1821.jpg)

version:
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-keyboard-aware-scroll-view": "^0.4.1",
    "react-navigation": "^1.0.0-beta.21"

--------------------------------------------------------------------------
I hope nav can be fixed at the top,what should I do,thanks~

**Comment by Swordsman-Inaction** [comment]
Don't wrap `nav` component inside the `aware` component.

**Comment by ayushnawani** [comment]
getting same issue here

**Comment by ayushnawani** [comment]
Can somebody help in this issue ?

**Comment by MR03web** [comment]
Then I used KeyboardAvoidingView.@ayushnawani

**Comment by ayushnawani** [comment]
@MR03web can you please share you code and screenshot, because i am stuck.

**Comment by MR03web** [comment]
https://github.com/MR03web/demo/tree/master/scrollViewDemo @ayushnawani

use android:windowSoftInputMode="adjustResize", not adjustPan

**Comment by ayushnawani** [comment]
thanks @MR03web , will check this.

**Comment by StepanNaryshkov** [comment]
@ayushnawani Did you fix it?

**Comment by ayushnawani** [comment]
@StepanNaryshkov. i was able to get fixed tab bar using [react-native-navbar](https://github.com/react-native-community/react-native-navbar) and using **adjustResize** . 
But i have multiple textinputs in single screen which just didn't working with adjustResize and react-native-keyboard-aware-scroll-view.

**Comment by alvaromb** [comment]
Hello, this seems an error with the combination of two libraries, not with `KeyboardAwareScrollView`. We're using it with `react-navigation` without any issue.
