### ISSUE TITLE
onKeyboardDidShow event

### ISSUE THREAD

**Issue by davidmessem** [APSL/react-native-keyboard-aware-scroll-view#208]
The `onKeyboardWillShow` event fires before the keyboard shows. 
I would like to call `scrollToEnd()` once the keyboard has finished showing. 
Therefore I suggest an enhancement where a `onKeyboardDidShow` or similar event is available. 

Currently I am using a timeout inside my `onKeyboardWillShow` function, but it's not ideal, since keyboard showing times can differ.

**Comment by alvaromb** [comment]
Hi @davidmessem!

Can you send us a PR for this? @Swordsman-Inaction or I will review it gladly.

Thanks!
