### ISSUE TITLE
Original position not adjusted when focussed field changes

### ISSUE THREAD

**Issue by iResources** [APSL/react-native-keyboard-aware-scroll-view#211]
If you:
1. Focus on an input
2. Focus on another input (without first unfocussing)
3. Unfocus

The view scrolls back to the original position instead of adjusting for input I was last editing.
Is this intended behaviour? I believe it should be aware of the last input I was editing.

**Comment by alvaromb** [comment]
It should be, but sometimes it doesn't work with the iOS simulator. Have you tried in a real device?

**Comment by tsugitta** [comment]
I'm facing the same issue on
```
react-native@0.51.0
react-native-keyboard-aware-scroll-view@0.4.1
```

**Comment by alvaromb** [comment]
Please update to `v0.4.2`. Ping me if it still doesn't work.

**Comment by rochapablo** [comment]
When I go field by field until the end and go back to the first field, the scroll it's not going back to the initial position.

```"react-native-keyboard-aware-scroll-view": "^0.4.2"```
