### ISSUE TITLE
how to popup screen scroll on click input

### ISSUE THREAD

**Issue by shashikantChetu** [APSL/react-native-keyboard-aware-scroll-view#213]
I have one problem I am using your package with react native but "KeyboardAwareScrollView" this function is not working to scroll screen after click on input text field .But i am using this with popup and code is ..
`<KeyboardAwareScrollView key={i} style={styles.modalView} automaticallyAdjustContentInsets={false}>`

**Comment by alvaromb** [comment]
Hello @shashikantChetu! Can you elaborate the issue properly? I cannot understand what's exactly your problem. Please post a source code snippet for reproducing the issue.

**Comment by shashikantChetu** [comment]
I am typing in text field screen is not scroll and i can't see what i am typing on field because keyword display hide to text field .
` <KeyboardAwareScrollView  style={styles.modalView} automaticallyAdjustContentInsets={false}>
	 <View style={styles.twoColWrapper}>
		<View style={{ width: '49%' }}>
		  <CustomTextInput
			label="Price"
			style={{ marginTop: 7 }}
			keyboardType="numeric"
			value={invoiceRecord.amount}
			onChangeText={text => onChangePrice(text)}
		  />
		</View>
		<View style={{ width: '49%', alignItems: 'center', justifyContent: 'center', paddingTop: 10 }}>
		  <Text style={{ fontSize: 10 }}>Total for Invoice</Text>
		  <Text style={{ fontSize: 17 }}>{accounting.formatMoney(invoiceRecord.amount, '$', 2)}</Text>
		</View>
	  </View>
 </KeyboardAwareScrollView>`
