### ISSUE TITLE
Problem with KeyboardAwareFlatlist on iOS

### ISSUE THREAD

**Issue by jhalborg** [APSL/react-native-keyboard-aware-scroll-view#219]
Hey, 

Thanks for a great lib!

I'm experiencing issues with the `KeyboardAwareFlatlist` on iOS only. I'm using version 0.4.3 along with Expo 24 / RN 0.51 / React 16

I'm using `KeyboardAwareScrollview` multiple places in my app, and it works great, for example:
https://gyazo.com/6bfd995630b70f7d129110914606e9d0

However, the `KeyboardAwareFlatlist` won't activate automatically if the software keyboard is enabled:
https://gyazo.com/382d77c4c2dadfb0b774318e735f075f

I can, however, force it to activate if I disable and then re-enable the keyboard (using cmd+K on emulator), but then the bottom padding is way too much:
https://gyazo.com/dddbd0cf55fadee5255815b51cb1fd46

I've tried printing out the `frames` on open and close for each of the scenarios, and it looks like this: 

```
Scrollview, works fine - open
{"easing":"keyboard","duration":250,"endCoordinates":{"height":271,"screenX":0,"width":414,"screenY":465},"startCoordinates":{"height":226,"screenX":0,"width":414,"screenY":736}}

Scrollview, works fine  - close
{"easing":"keyboard","duration":250,"endCoordinates":{"height":0,"screenX":0,"width":414,"screenY":736},"startCoordinates":{"height":271,"screenX":0,"width":414,"screenY":465}}

CommentsList open (didn't work)
{"easing":"keyboard","duration":250,"endCoordinates":{"height":271,"screenX":0,"width":414,"screenY":465},"startCoordinates":{"height":226,"screenX":0,"width":414,"screenY":736}}

CommentsList close (didn't work)
{"easing":"keyboard","duration":250,"endCoordinates":{"height":0,"screenX":0,"width":414,"screenY":736},"startCoordinates":{"height":271,"screenX":0,"width":414,"screenY":465}}

CommentsList open (forced with cmd+K)
{"easing":"keyboard","duration":250,"endCoordinates":{"height":226,"screenX":0,"width":414,"screenY":510},"startCoordinates":{"height":0,"screenX":0,"width":414,"screenY":736}}
{"easing":"easeInEaseOut","duration":0,"endCoordinates":{"height":271,"screenX":0,"width":414,"screenY":465},"startCoordinates":{"height":226,"screenX":0,"width":414,"screenY":510}}
{"easing":"keyboard","duration":250,"endCoordinates":{"height":271,"screenX":0,"width":414,"screenY":465},"startCoordinates":{"height":226,"screenX":0,"width":414,"screenY":510}}

CommentsList close (forced with cmd+K)
{"easing":"keyboard","duration":250,"endCoordinates":{"height":0,"screenX":0,"width":414,"screenY":736},"startCoordinates":{"height":271,"screenX":0,"width":414,"screenY":465}}
```

The code used for the flatlist looks like this:
```
import { KeyboardAwareFlatList } from 'react-native-keyboard-aware-scroll-view';
...
<KeyboardAwareFlatList
          inverted={true}
          renderItem={this.renderRow}
          keyExtractor={this.keyExtractor}
          refreshing={this.props.fetching}
          ListEmptyComponent={
            <EmptyViewForLists
              text={`No comments yet! Be the first...`}
              showTitle={false}
            />
          }
          data={this.props.comments}
          onEndReached={this.props.loadMore}
          onEndReachedThreshold={0.8}
          ListHeaderComponent={this.renderHeader}
          keyboardDismissMode="on-drag"
          keyboardShouldPersistTaps="handled"
          onKeyboardWillShow={frames => {
            console.log(TAG, `\n${JSON.stringify(frames)}\n`);
          }}
          onKeyboardWillHide={frames => {
            console.log(TAG, `\n${JSON.stringify(frames)}\n`);
          }}
        />
```

On Android, both work as expected. On physical device, the result is that of the middle scenario where nothing happens, even if dismissing the keyboard by dragging on the list and reopening it. 

Snack for demonstration: https://snack.expo.io/Bk1SBulLG

The snack is more as a gist, as it seems that `KeyboardAwareScrollview` doesn't even work there, unless I'm missing something? https://snack.expo.io/BklPMulUG

What could be the issue? Let me know if I can be of further assistance in debugging

**Comment by marlonbrgomes** [comment]
Hey bro, I'm facing the same issue here and got a workaround to solve that. I hope it solves your issue too.

On a KeyboardAwareFlatlist I have added this prop "onKeyboardWillShow" and added as callback a function to scroll to offset X, in my case (0 - screenY / 2 ) was enough to be showed by my view with the active keyboard.

```
onKeyboardWillShow={({ endCoordinates: { screenY } }) => {
  if (scrollRef && Platform.OS === 'ios') {
    // This setTimeout is pretty important because the application has to wait til the keyboardshow event is completed to scroll to the offset. If you do not set it the scroll will just "shake" the screen

    setTimeout(() => scrollRef.scrollToOffset({ animated: true, offset: 0 - (screenY / 2) }), 300);
  }
}}
```

**Comment by jhalborg** [comment]
Cool, thanks, @marlonbrgomes . I ended up using a different lib for this one case because I couldn't wait, [the keyboard spacer](https://github.com/Andr3wHur5t/react-native-keyboard-spacer).

**Comment by alvaromb** [comment]
Hey! What do you really want to achieve in this case? Cannot open the `gyazo` examples.

**Comment by jhalborg** [comment]
Hey :) Normal behavior, that the view would adjust to the keyboard instead of hiding behind it. "Cannot open the gyazo examples" - what happens when you click them? Those gifs would explain it quite well I think :)

**Comment by julianorafael** [comment]
I'm also facing this problem. Gonna try @marlonbrgomes solutions later in the day. I'll give you guys an update on that asap.

**Comment by dop3** [comment]
Same issue here... the very same as @jhalborg described.
@thefrontendwizard , any news on this?

**Comment by rborn** [comment]
I'll close this for being very old. Thanks for all the comments 😻 
Please ping me if you still see it as an issue.

**Comment by amaljosea** [comment]
I am facing the issue

    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react": "16.11.0",
    "react-native": "0.62.2"

Thanks
