### ISSUE TITLE
Not working on Android 4.4.2

### ISSUE THREAD

**Issue by 4external** [APSL/react-native-keyboard-aware-scroll-view#223]
Hi!

Scrolling dont work on Android 4.4.2(Samsung s4 mini).

If content height on view is not enough for enabling scrolling, but keyboard overlap some textinputs, scrolling not enabled.

If content height on view enough for enabling scrolling, and keyboard overlap some textinputs, scrolling is working but on value  like without keyboard. 

It seems not calculate keyboard height.

On android 5.1 and ios 10 it work like expected.

Component version 0.4.3
Expo.
---
Environment:
  OS: macOS Sierra 10.12.6
  Node: 7.10.1
  Yarn: Not Found
  npm: 4.2.0
  Watchman: 4.7.0
  Xcode: Xcode 8.3.2 Build version 8E2002
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

**Comment by alvaromb** [comment]
Scroll support in Android is provided through `windowSoftInputMode` in the manifest file.
