### ISSUE TITLE
undefined _this._rnkasv_keyboardView.getScrollResponder

### ISSUE THREAD

**Issue by haofeng123** [APSL/react-native-keyboard-aware-scroll-view#224]

**Comment by alvaromb** [comment]
Hello!

Please provide some source code in order to be able to help you.

Thanks.

**Comment by xralphack** [comment]
Hi, I used the react-native-draggable-flatlist library.

I want to add keyboard avoid functionality to this flatlist.

```
import React, { Component } from "react";
import {
  KeyboardAwareFlatList,
  listenToKeyboardEvents
} from "react-native-keyboard-aware-scroll-view";
import DraggableFlatList from "react-native-draggable-flatlist";

export default listenToKeyboardEvents(DraggableFlatList);
```

after click something in this component, I will get
undefined _this._rnkasv_keyboardView.getScrollResponder error.
any suggestion?
