### ISSUE TITLE
IOS not scrolling fully back to top position

### ISSUE THREAD

**Issue by Dhanraj-bidchat** [APSL/react-native-keyboard-aware-scroll-view#225]
On IOS device, keyboard-aware-scroll-view not properly going back to top position.
keyboard-aware-scroll-view adds some padding[white space]  once scroll down with default scrolling animation effect.

please refer this link: 
https://drive.google.com/open?id=12mX28K8PLNGJLwu3gSOv4uPhwdDJQJeO

**Comment by countach74** [comment]
I have this problem as well.

**Comment by alvaromb** [comment]
Please check the ScrollView props, this is an upstream issue with it http://facebook.github.io/react-native/docs/scrollview.html

**Comment by Geforceyu** [comment]
I have the problem too,did solved？

**Comment by superandrew213** [comment]
@Geforceyu try setting `automaticallyAdjustContentInsets={false}`
