### ISSUE TITLE
enableAutomaticScroll disables scroll entirely

### ISSUE THREAD

**Issue by reddo** [APSL/react-native-keyboard-aware-scroll-view#229]
Setting the `enableAutomaticScroll` prop to false disables scrolling entirely, even when `scrollEnabled` is set to `true`. I'm using version 0.4.4.

**Comment by alvaromb** [comment]
Not experiencing this in any of our apps, can you show us some source code?

**Comment by biboukat** [comment]
Hi, I can't disable "enableAutomaticScroll"
<KeyboardAwareScrollView keyboardShouldPersistTaps="always" enableAutomaticScroll={false}>

**Comment by BenjaminHerholz** [comment]
I have the sam problem. as @biboukat 
Any news on this?

**Comment by rborn** [comment]
I'll close this for being very old. Thanks for all the comments 😻 
Please ping me if you still see it as an issue.

**Comment by sijju** [comment]
This is still an issue.
