### ISSUE TITLE
viewIsInsideTabBar is not working

### ISSUE THREAD

**Issue by ajoshdee** [APSL/react-native-keyboard-aware-scroll-view#23]
Hi viewIsInsideTabBar props is not working, I want to remove the offset at the bottom but i can't remove it either way

**Comment by alvaromb** [comment]
Hello!

I'm currently using `viewIsInsideTabBar` with success. Can you post a visual example of what's actually not working and your source code? Thanks for reporting!

**Comment by ajoshdee** [comment]
I can't remove the extra offset at the bottom

**Comment by alvaromb** [comment]
Can you post your code? Can't help without that.

**Comment by ajoshdee** [comment]
'<KeyboardAwareScrollView>
  <View>
    <TextInput />
  </View>
</KeyboardAwareScrollView>'

**Comment by alvaromb** [comment]
Try to add this `automaticallyAdjustContentInsets={false}` to your scroll.

**Comment by ajoshdee** [comment]
nope, still there

**Comment by alvaromb** [comment]
Sorry I can't help you any further if you don't provide a visual example of what's not working or your actual source code.

**Comment by ajoshdee** [comment]
![img_1302](https://cloud.githubusercontent.com/assets/7309782/15702752/5a4f1202-2814-11e6-9bc4-56250eb5062a.jpg)

**Comment by ajoshdee** [comment]
the scroll ended there, so there's obviously an offset. I just used your example code.

**Comment by alvaromb** [comment]
With the latest version of the library, this example is currently working inside a `TabBar`:

```js
<KeyboardAwareScrollView ref='scroll'
        style={styles.container}
        contentContainerStyle={styles.contentContainer}
        keyboardShouldPersistTaps={true}
        viewIsInsideTabBar={true}
        automaticallyAdjustContentInsets={false}>
...
</KeyboardAwareScrollView>

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  contentContainer: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 20,
  }
})
```

Try to adapt it to your source code.

**Comment by ajoshdee** [comment]
still not working, though it became normal after i dismissed the keypad.

**Comment by ajoshdee** [comment]
Using the react scrollview works too, so i don't think there's a problem with my styles

**Comment by alvaromb** [comment]
Try to remove `viewIsInsideTabBar` prop and set your own `contentInset` props.

**Comment by ajoshdee** [comment]
Oh that worked for me thanks

**Comment by jtanori** [comment]
I had to set the height of the KeyboardAwareScrollView for this to work, have you faced that @alvaromb ?

**Comment by alvaromb** [comment]
Nope @jtanori!

What's exactly your issue? Just FYI, I'll deprecate this library soon, it seems that RN now includes a 'keyboard avoiding view' that does the same. Might be worth checking it out.
