### ISSUE TITLE
Gives error in a fresh app

### ISSUE THREAD

**Issue by potasium** [APSL/react-native-keyboard-aware-scroll-view#230]
I tried on fresh apps but always give this error. When import on the top: _unable to resolve module 'react-native-keyboard-aware-scrollview'_

"dependencies": {
    "react": "16.2.0",
    "react-native": "0.53.3",
    "react-native-keyboard-aware-scroll-view": "^0.4.4"
  },

**Comment by chrismcamp** [comment]
@potasium `react-native-keyboard-aware-scrollview` is not the same as `react-native-keyboard-aware-scroll-view`
