### ISSUE TITLE
TextInput is only showed half in iPhone X

### ISSUE THREAD

**Issue by happyeverydayzhh** [APSL/react-native-keyboard-aware-scroll-view#232]
I use TextInput as Flatlist's cell, and iPhone 6s is perfect. But in iPhone X, TextInput is only showed half as below.

![3241520236512_ pic_hd](https://user-images.githubusercontent.com/5198326/36963321-b2168fd8-208d-11e8-93e5-aa396d7b2bec.jpg)

react-native: 0.51.0
react-native-cli: 2.0.1

**Comment by happyeverydayzhh** [comment]
I fixed it with KeyboardAwareFlatList

**Comment by 404sand808s** [comment]
I'm having the same issue (only on iPhone X), on latest version of this repo and using react-navigation. I'm already using KeyboardAwareFlatList though. How did the switch to this component help?

Thanks.
