### ISSUE TITLE
Double click

### ISSUE THREAD

**Issue by NikoMontana** [APSL/react-native-keyboard-aware-scroll-view#233]
I have created a TextInput and a Button, after setting the text i want to click on the button but the behavior is weird. I have to click 2 times on the button, the first time is to close the keyboard, the second click is then calling the onPress. Is there a workaround for this?

**Comment by alvaromb** [comment]
Please check the `ScrollView` props, specifically https://facebook.github.io/react-native/docs/scrollview.html#keyboarddismissmode

**Comment by antofa** [comment]
@NikoMontana, Property keyboardShouldPersistTaps='always' should solve your problem.

https://facebook.github.io/react-native/docs/scrollview.html#keyboardshouldpersisttaps

**Comment by NikoMontana** [comment]
I have tried this back in time when I was having problems with it. There was something else weird going on for this solution @antofa. 

I finally decided not to use this lib. I went for KeyboardAvoidingView from React Native itself. Here is a short snippet if anyone else would ever need it.

`      <TouchableWithoutFeedback onPress={() => Keyboard.dismiss()}>
        <View useSafeArea={true} style={{ flex: 1 }}>
          <KeyboardAvoidingView behavior="position"> ....`

**Comment by GoshaEgorian** [comment]
You have to set `keyboardShouldPersistTaps='always'` on `KeyboardAwareScrollView` component

**Comment by thaoth-gem** [comment]
@GoshaEgorian but set keyboardShouldPersistTaps to always make touch outsite keyboard cant dismiss , how can i make only its working on my button .

**Comment by tuannkop** [comment]
@GoshaEgorian but set keyboardShouldPersistTaps to always make touch outsite keyboard cant dismiss , how can i make only its working on my button .

**Comment by Liqiankun** [comment]
@GoshaEgorian The button works but keyboard does not dismiss!

**Comment by utsav** [comment]
I used keyboardShouldPersistTaps='handled' and it work like charm

**Comment by Liqiankun** [comment]
Set keyboardShouldPersistTaps='always'
```
onPress={() => {
    Keyboard.dismiss()
}}
```

**Comment by guillaume-at-palo** [comment]
On my side <KeyboardAwareScrollView keyboardShouldPersistTaps="handled"> really do the job.
I can click on buttons only once when the keyboard is open and the keyboard dismiss when I click outside text fields

**Comment by rajitha302** [comment]
In my case I fixed the double tap issue by passing this prop to `ScrollableTabView` component.
`contentProps={{keyboardShouldPersistTaps: 'always'}}`

**Comment by abdulla-khalil** [comment]
@rajitha302 
can you please elaborate on you solution? how did you pass the prop to ScrollableTabView and what did you pass? 
many thanks

**Comment by rajitha302** [comment]
pass "keyboardShouldPersistTaps: 'always'" to contentProps inside
ScrollableTabView Component

contentProps={{keyboardShouldPersistTaps: 'always'}}

**Comment by Shenon69** [comment]
As @guillaume-at-palo mentioned pass the _keyboardShouldPersistTaps="handled"_ prop to `KeyboardAwareScrollView`. If you have a `ScrollView` within the `KeyboardAwareScrollView` tags then pass the _keyboardShouldPersistTaps="handled"_  prop to that `ScrollView` as well.

```
<KeyboardAwareScrollView style={styles.container} keyboardShouldPersistTaps="handled" extraHeight={200} bounces={false} enableOnAndroid>
        <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ flex: 1 }} bounces={false}>
               <FormHeader />
               <LoginForm />
        </ScrollView>
</KeyboardAwareScrollView>
```
