### ISSUE TITLE
Wrong position when using react-native-navigation from wix

### ISSUE THREAD

**Issue by brunolemos** [APSL/react-native-keyboard-aware-scroll-view#234]
When using the wix navigator and: 

- `windowSoftInputMode="adjustResize"`, it scrolls to the wrong position (maybe ~40px off?)
- `windowSoftInputMode="adjustPan"`, it removes the navbar from the screen, which is not what I want
- inside a modal, it scrolls to the wrong position on input focus.

**Comment by brunolemos** [comment]
Setting `extraHeight={Platform.select({ android: 200 })}` helps.

**Comment by CptFabulouso** [comment]
and which `windowSoftInputMode` you use with that?
