### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by OleksandrBezhan** [APSL/react-native-keyboard-aware-scroll-view#24]
I cann't get it to work properly. Here is how it looks for me:

[http://i.imgur.com/nO1m1fg.gif](url)

```javascript
'use strict'

import React, {
    Component,
    AppRegistry,
    Text,
    TextInput,
    View,
    ScrollView,
} from 'react-native'
import { KeyboardAwareScrollView, } from 'react-native-keyboard-aware-scroll-view'

class KeyboardScrollTest extends Component {
    render() {
        return (
            <View style={{height:600}}>
                <View style={{flex:3}}></View>
                <View style={{flex:1}}>
                    <KeyboardAwareScrollView>
                        <TextInput style={{bordrerColor:'black',borderWidth:1,height:40}} />
                    </KeyboardAwareScrollView>
                </View>
            </View>
        )
    }
}

AppRegistry.registerComponent('KeyboardScrollTest', () => KeyboardScrollTest)
```

I've pushed the code [https://github.com/OleksandrBezhan/react-native-keyboard-aware-scroll-view-test](url)

**Comment by michaeljgilmore** [comment]
If you are getting an issue where RCTShadowView is part of the error this is an issue that the author has pushed a fix to the main react native repo and is awaiting a fix for.  There is a workaround but it's pretty complicated.  We are all patiently waiting at the moment.

**Comment by alvaromb** [comment]
Thanks!

I hope it gets merged soon but in the meantime you can add these changes to your React Native installation https://github.com/facebook/react-native/pull/7876
