### ISSUE TITLE
tap on another textinput hide keyboard so need to tap again on textinput for keyboard open and type

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [APSL/react-native-keyboard-aware-scroll-view#240]
tap on another textinput hide keyboard so need to tap again on textinput for keyboard open and type

**Comment by davae1an** [comment]
having this same issue

**Comment by alvaromb** [comment]
http://facebook.github.io/react-native/docs/scrollview.html#keyboardshouldpersisttaps
