### ISSUE TITLE
keyboardShouldPersistTaps="never" doesn't dismiss keyboard between TextInputs

### ISSUE THREAD

**Issue by ltankey** [APSL/react-native-keyboard-aware-scroll-view#243]
I have a setup, described in [this](https://snack.expo.io/ByvNnunoG) Snack.

I am using a `KeyboardAwareScrollView` with `keyboardShouldPersistTaps="never"`, so that a click away  from a form input always dismisses the keyboard.  If I press into one of the text inputs, and then press outside of it, the keyboard dismisses as is expected.  If I press into one of the text inputs, and then immediately into another, I can then not immediately dismiss the keyboard.

As I am also using [react-native-modal-selector](https://github.com/peacechen/react-native-modal-selector), this means that a user is able to launch a modal for a choice list, and when they choose an item, they are returned back to the previous field with the focus, and the keyboard open. 

Should `keyboardShouldPersistTaps="never"` mean that even taps between text inputs should dismiss the keyboard?

I am using:

```
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-keyboard-aware-scroll-view": "^0.5.0",
```

**Comment by bekkii77** [comment]
I am experiencing the same thing.  I changed it to `keyboardShouldPersistTaps="handled"` and now the keyboard is dismissing no matter what.  I haven't gotten far enough to see if there are other side effects to using "handled".

**Comment by ltankey** [comment]
Turns out this bug is coming from upstream - https://github.com/facebook/react-native/issues/17252
