### ISSUE TITLE
extraScrollHeight reverting back after completed

### ISSUE THREAD

**Issue by GraysonB** [APSL/react-native-keyboard-aware-scroll-view#244]
Steps:
1. Add extraScrollHeight to a KeyBoardAwareScrollView
2. Run application
3. Focus on textinput

Expected Behavior:
The textinput is elevated above the keyboard by extraScrollHeight space.

Actual Behavior:
The textinput is elevated above the keyboard by extraScrollHeight space then immediately goes back down to the original height.

Note: when testing I did 10. When I changed it to 15, it showed more padding (roughly 5), so it appears it is reverting by a fixed amount, maybe 10.

New Note: it seems to only be the first time it is focused. When I hit "return" and close the keyboard, replicating the steps leads to a corrected adjusted height of 15.

**Comment by GraysonB** [comment]
Note: when testing I did 10. When I changed it to 15, it showed more padding (roughly 5), so it appears it is reverting by a fixed amount, maybe 10.

**Comment by elijahmurray** [comment]
I have this; it appears to affect only my `keyboardType="number-pad"` inputs.

**Comment by Sterlingryan** [comment]
Any fix for this ?

**Comment by rborn** [comment]
I'll close this for being very old. Thanks for all the comments 😻 
Please ping me if you still see it as an issue.

**Comment by moGeekHex** [comment]
I have some issue
