### ISSUE TITLE
the scroll is going up on focus element at the bottom

### ISSUE THREAD

**Issue by Slader10** [APSL/react-native-keyboard-aware-scroll-view#245]
i'm working on a very long form, when you try to write something on the last inputs the compoents scroll up all the form and you cant see what you are writing.

**Comment by boldarevbogdan** [comment]
Faced the same problem. And I think i solved it just adding extraScrollHeight property with value 50 in my case.

**Comment by alvaromb** [comment]
Should only happen in simulator.
