### ISSUE TITLE
KeyboardAwareSectionList multi TextInput,it doesn't work

### ISSUE THREAD

**Issue by androidwt** [APSL/react-native-keyboard-aware-scroll-view#246]
this KeyboardAwareSectionList is so poor

**Comment by oznekenzo** [comment]
The docs for this are very incomplete!!

**Comment by oznekenzo** [comment]
For anyone having issues, I figured it out after some hours:

You do not pass KeyboardAwareSectionList a section list as children as is in the docs, you ought to configure a the native SectionList component per the react native docs, then switch out the `SectionList` component with `KeyboardAwareSectionList` with the exact same configuration.
