### ISSUE TITLE
Keyboard scroll with Flatlist

### ISSUE THREAD

**Issue by shimil2017** [APSL/react-native-keyboard-aware-scroll-view#247]
Hi,
My flatlist getting srolled more than keyboard height .I have text input in each render item.its working for to text input but for bottom it scrolling to much
![screen shot 2018-04-26 at 11 34 21 am](https://user-images.githubusercontent.com/29571718/39288546-1018e8d4-4946-11e8-8fab-cf05ac9e6aed.png)

**Comment by neilzhengzx** [comment]
same problem!

**Comment by alvaromb** [comment]
Hi @shimil2017! Can you explain a little bit more your issue?

**Comment by rborn** [comment]
I'll close this for being very old. Thanks for all the comments 😻 
Please ping me if you still see it as an issue.
