### ISSUE TITLE
Example for Use with Child Components?

### ISSUE THREAD

**Issue by seenickcode** [APSL/react-native-keyboard-aware-scroll-view#249]
Hello there,

I have a TextInput field wrapped in its own component, where I have a `KeyboardAwareScrollView` in a parent component. 

Is there an example to get this working?  It doesn't seem to work in this situation.

Thanks,

**Comment by bugs181** [comment]
Can you provide more details besides "It doesn't seem to work ..."? I have a `TextInput` being wrapped inside of a custom component that works just fine. Perhaps you can provide some example code of what you've tried and I can help.

**Comment by rborn** [comment]
I'll close this for being very old. Thanks for all the comments 😻 
Please ping me if you still see it as an issue.

**Comment by shubhamsurvev2stech** [comment]
same issue with me

**Comment by bugs181** [comment]
@shubhamsurvev2stech please open a new issue and be as informative as possible. Providing what you expect it to do versus what is happening.
