### ISSUE TITLE
Crash when two KASV are rendered and one TextInput gets focused

### ISSUE THREAD

**Issue by alvaromb** [APSL/react-native-keyboard-aware-scroll-view#25]

**Comment by sjchmiela** [comment]
Bump

**Comment by ararog** [comment]
I would say its one of the most important fixes, I'm facing this issue right now.

**Comment by pimkle** [comment]
I'm unsubscribing this issue. Here's how I resolve this. The crash happens randomly, certain pages do every time, some pages never crash. I even removed everything in the page except the InputText, the page still, crashed. So I abandoned this wonderful control, and go to an IOS developer for help. Yeah, the keyboard problem only happens on IOS devices, and he recommend me an IOS plugin:IQKeyboardManager-master, and I just simple drag the folder into my Xcode, and the problem was fixed perfectly. If you are not a professional IOS developer, and you don't know how to put the IQKeyboardManager plugin into your project, leave a comment, I may tell you the detail.

**Comment by alvaromb** [comment]
Hello @ararog @pimkle!

**DISCLAIMER**
I'm a professional iOS developer and mobile team lead currently in my company 😆 

**Issue**
Now about the issue. I've sent a PR that has been accepted and will be introduced into React Native 0.32 that solves this issue. For more info and context, please read my explanation here https://github.com/facebook/react-native/pull/7876.

In this library you have a branch that, if you use the code of my PR, completely solves the issue (https://github.com/APSL/react-native-keyboard-aware-scroll-view/tree/ancestor_check). I'm waiting the release of React Native to merge & release the `ancestor_check` branch.

And, in this case, I prefer to provide a JavaScript solution to the keyboard & scroll view problem. Once the fix has landed into the React Native core, I'll be able to dig deep into the Android support and you'll have a component working for both platforms without any other dependencies.

**Comment by alvaromb** [comment]
The crash do not happen randomly, @pimkle, it does happen when you have two scroll views listening for keyboard events. Please do read my comments in the React Native PR.

**Comment by empitechathu** [comment]
any solution for this .. nothing is working here :( :(

**Comment by alvaromb** [comment]
Hello @empitechathu!

Everything is working here, we're using the component with the patch in all our apps. Please install the library from the `ancestor_check` branch and apply the changes in the React Native PR. Once my changes land in a RN release, I'll release the `ancestor_check` branch.

**Comment by pimkle** [comment]
@alvaromb I got that! I'll try it someday. Thanks! 😁

**Comment by alvaromb** [comment]
Please be patient, the PR should land in React Native 0.32 (or 0.33). In the meantime, you can manually add the code to bypass the issue.

**Comment by Swordsman-Inaction** [comment]
@alvaromb 0.32 is released, your PR is in it.

**Comment by alvaromb** [comment]
Thanks for the info @Swordsman-Inaction!

I'll release a new version of the component today :)

**Comment by alvaromb** [comment]
I won't have enough time for a release today, haven't tested all the features yet.

Expect a release tomorrow.

Thanks!

**Comment by alvaromb** [comment]
This is the PR https://github.com/APSL/react-native-keyboard-aware-scroll-view/pull/57

**Comment by alvaromb** [comment]
@Swordsman-Inaction just FYI, `0.32` isn't released yet, only the RC-0.

**Comment by alvaromb** [comment]
Merged #57
