### ISSUE TITLE
Webview calls the keyboard, the keyboard will block view

### ISSUE THREAD

**Issue by YanfangLi248** [APSL/react-native-keyboard-aware-scroll-view#252]
I load editor.html with webview and add the webview to component, there is textarea in html, it can call keyboard. I add the component to KeyboardAwareScrollView. I found the keyboard cover view.

**Comment by alvaromb** [comment]
This component is not ready to be used with `WebView`s. PRs accepted!

**Comment by Donhv** [comment]
` this.keyboardDidShowListener = Keyboard.addListener(
      "keyboardDidShow",
      frames => {
        if (!frames.endCoordinates) return;
        this.setState({ keyboardSpace: frames.endCoordinates.height });
      }
    );
    this.keyboardDidHideListener = Keyboard.addListener(
      "keyboardDidHide",
      frames => {
        this.setState({ keyboardSpace: 0 });
      }
    );`

And Use         <View style={{ height: this.state.keyboardSpace }} /> under your webview
