### ISSUE TITLE
I can't find KeyboardAwareSectionView

### ISSUE THREAD

**Issue by tuononh** [APSL/react-native-keyboard-aware-scroll-view#255]
Is this not supported yet?

**Comment by zachrnolan** [comment]
I think you're looking for `KeyboardAwareSectionList`.

**Comment by alvaromb** [comment]
@tuononh you're looking for https://github.com/APSL/react-native-keyboard-aware-scroll-view/blob/master/lib/KeyboardAwareSectionList.js
