### ISSUE TITLE
did not work on react-native @0.56.0

### ISSUE THREAD

**Issue by simonwang6666** [APSL/react-native-keyboard-aware-scroll-view#281]
the keyboard is not appear below the input/textarea after i upgrade react-native @0.56.0 which works well @0.55.x

**Comment by wangshangming** [comment]
![wechatsight47](https://user-images.githubusercontent.com/12669392/42690536-23dec266-86d7-11e8-9c83-2dc08dc75eba.gif)

**Comment by alvaromb** [comment]
Thanks for reporting @wangshangming!

Can you put up a code example?

**Comment by wangshangming** [comment]
@alvaromb 
glad to have your apply^-^
my code 
```
<KeyboardAwareScrollView>
       <View style={styles.loginForm}>
            <YqgInput
                    displayType="transparent"
                    style={styles.loginFormItem}
                    label="userName"
                    onChange={text => this.setState({username: text})}
                   value={username}
            />
     </View>
                .....
</KeyboardAwareScrollView>
```
I just simply use KeyboardAwareScrollView as my root element with no extra props,
YqgInput is a simple encapsulation of TextInput using an UI Frame called antd-mobile-rn
After i using react-native-git-upgrade to upgrade my react-native's version from 0.55.4 to 0.56.0,
it did not work.  i think maybe some changes of feature by RN causing Props `enableAutomaticScroll` does not work.
