### ISSUE TITLE
use KeyboardAwareSectionList,How can I get the x,y position of the sectionHead，And jump past.

### ISSUE THREAD

**Issue by wanyao1990** [APSL/react-native-keyboard-aware-scroll-view#282]
use SectionList,i can use scrollToLocation,use sectionIndex.But use KeyboardAwareSectionList,i cannot get the x,y.

**Comment by Olezhka-web** [comment]
If someone is using `KeyboardAwareSectionList` and cannot access the `scrollToLocation` method, use `innerRef` instead of `ref`:

```
const myRef = useRef(null);

<KeyboardAwareSectionList 
   innerRef={(ref) => (myRef.current = ref)}
   ...
/>

myRef.current?.scrollToLocation
```

As an alternative (depending on your requirements), you can replace it with `KeyboardAwareFlatList` using `innerRef` and use the `scrollToIndex` method.
