### ISSUE TITLE
extraScrollHeight issues

### ISSUE THREAD

**Issue by diegolmello** [APSL/react-native-keyboard-aware-scroll-view#289]
Hey, guys.
I found a bug when you have a button at the bottom of the form.
Typically, you don't want your user to dismiss keyboard and only then show a "send" button, right?
That's is the use case of `extraScrollHeight`, so the user can enter values and submit the form.

Below I uploaded a gif showing that works as expected, but it causes two bugs:
1) if you scroll while the keyboard is opened, it adds empty space and the bottom.
2) after keyboard is dismissed, the same empty space is there.

![keyboard-space](https://user-images.githubusercontent.com/804994/43655727-3f46a618-9726-11e8-93ab-e4e35b3d6a3b.gif)

Code:
```jsx
render() {
    return (
        <KeyboardAwareScrollView extraScrollHeight={70}>
            <View style={{ padding: 20 }}>
                <TextInput />
                <TextInput />
                <TextInput />
                <TextInput />
                <TextInput />
                <TextInput />
                <TextInput />
                <TextInput />
                <TextInput />
                <TextInput />
                <TextInput />
                <TextInput />
                <TextInput />
                <TextInput />
                <TextInput />
                <TextInput />
                <TextInput />
                <TouchableOpacity>
                    <View style={{ padding: 10, backgroundColor: '#ccc' }}>
                        <Text>SEND</Text>
                    </View>
                </TouchableOpacity>
            </View>
        </KeyboardAwareScrollView>
    );
}
```

**Comment by hiradarshadi** [comment]
same issue

**Comment by yongching** [comment]
same issue +1

**Comment by spiritman110** [comment]
same issue +1, would be great if this could get patched up

**Comment by AaronDRS** [comment]
I'm facing the same issue. After the keyboard hides, there is a gap at the bottom.

**Comment by luizParreira** [comment]
I have been using a fork that fixes this the same way #279 does, I can confirm it fixes the issue.
https://github.com/luizParreira/react-native-keyboard-aware-scroll-view

**Comment by AaronDRS** [comment]
It's working now. It was an animation not updating the right time causing wrong values in my UI, my bad. 
I don't have any issues with the package.

**Comment by andrej-kuznetsov** [comment]
"react-native-keyboard-aware-scroll-view": "^0.8.0",
"react-native": "0.55.4",
![hallo](https://user-images.githubusercontent.com/45454024/51790325-4f444600-219c-11e9-8557-87d30dde899f.gif)

**Comment by IsharaHansaka** [comment]
same issue

**Comment by NathanDsouza** [comment]
@alvaromb Hey is it possible to re-open this? I believe this is still an issue

**Comment by balzdur** [comment]
I'm convinced this is linked to a bug in the implementation of `extraScrollHeight`.

In the meantime someone found the issue, I found a way to bypass it :

```
render() {
    return (
        <KeyboardAwareScrollView 
          onKeyboardWillShow={() => {
            this.setState({extraScrollHeight: 70});
          }}
          onKeyboardWillHide={() => {
            this.setState({extraScrollHeight: 0});
          }}
          extraScrollHeight={this.state.extraScrollHeight}>
            <View style={{ padding: 20 }}>
                <TextInput />
                ...
                <TextInput />
                <TextInput />
                <TouchableOpacity>
                    <View style={{ padding: 10, backgroundColor: '#ccc' }}>
                        <Text>SEND</Text>
                    </View>
                </TouchableOpacity>
            </View>
        </KeyboardAwareScrollView>
    );
}
```

**Comment by Donhv** [comment]
same issue. both android & iOS.

**Comment by devinjameson** [comment]
This is an issue related to the bottom tab bar. I fixed it by getting the height of the tab bar on app load, saving it to state in a context, then setting the extraScrollHeight to the negative of that value.
```
  // Context
  const [tabBarHeight, setTabBarHeight] = useState<TabBarHeight>(null)

  const updateTabBarHeight = (nextTabBarHeight: TabBarHeight): void => {
    setTabBarHeight(nextTabBarHeight)
  }
```
```
// Tab Bar
const { updateTabBarHeight } = useLayoutContext()   

const handleOnLayout = (event: LayoutChangeEvent): void => {
  const { height } = event.nativeEvent.layout
  updateTabBarHeight(height)
}

return (
  <View
    style={{
      ...style.tabBarContainer,
      paddingBottom: insets.bottom + Sizing.x10,
    }}
    onLayout={handleOnLayout}
  >
    {tabs.map(toTabButton)}
  </View>
)
```
```
// View
<KeyboardAwareScrollView
  style={style.innerFiltersContainer}
  contentContainerStyle={style.innerFiltersContentContainer}
  alwaysBounceVertical={false}
  extraScrollHeight={tabBarHeight ? -tabBarHeight : 0}
>
```

**Comment by jordiup** [comment]
I'm having the same issue. 

Using an `extraScrollHeight` offset for the tabs didn't seem to work 🤔 

The issue only seems to occur when you get to the bottom of the `< KeyboardAwareScrollView />`, where dismissing the keyboard leaves a void. 

I'm thinking you could do something that dynamically makes use of the following props (only when bottom fields are dismissed/blurred)? Plz let me know if anyone has any luck 

```
  /**
   * Coordinates that will be used to reset the scroll when the keyboard hides.
   *
   * @type {{
   *         x: number,
   *         y: number
   *     }}
   * @memberof KeyboardAwareProps
   */
  resetScrollToCoords?: {
    x: number
    y: number
  }

  /**
   * Lets the user enable or disable automatic resetScrollToCoords
   *
   * @type {boolean}
   * @memberof KeyboardAwareProps
   */
  enableResetScrollToCoords?: boolean
```
(/react-native-keyboard-aware-scroll-view/index.d.ts)
