### ISSUE TITLE
Does not play friendly with TypeScript

### ISSUE THREAD

**Issue by ethanneff** [APSL/react-native-keyboard-aware-scroll-view#293]
Errors:
<img width="547" alt="screen shot 2018-08-13 at 8 51 43 am" src="https://user-images.githubusercontent.com/2933593/44043017-aa187158-9ed6-11e8-943d-6ea079698768.png">
<img width="556" alt="screen shot 2018-08-13 at 8 52 17 am" src="https://user-images.githubusercontent.com/2933593/44043018-ab285b26-9ed6-11e8-8c78-16f92dbab755.png">

**Comment by alvaromb** [comment]
https://github.com/Microsoft/vscode/issues/15171
