### ISSUE TITLE
How to scrollToView - into FlatList.Item ?

### ISSUE THREAD

**Issue by NikoMontana** [APSL/react-native-keyboard-aware-scroll-view#296]
I am writing comments-section and want to scroll to the new item onSend().
The KeyboardAwarScrollView is wrapped around a Flatlist.

          <KeyboardAwareScrollView
            enableOnAndroid={true}
            viewIsInsideTabBar={true}
            extraScrollHeight={Platform.OS === "ios" ? 70 : -53}
          >

                  <FlatList
                    data={this.state.task_comments}
                    keyExtractor={comment => comment.commentID}
                    scrollEnabled={false}
                    style={{ marginTop: 10 }}
                    renderItem={({ item: comment }) => (
                      <CommentItem comment={comment} isSubComment={false} />
                    )}
                    initialNumToRender={3}
                    maxToRenderPerBatch={10}
                  />

         </KeyboardAwareScrollView>

**Comment by alvaromb** [comment]
Please don't use nested scroll views. Instead, use only `KeyboardAwareFlatList` and navigate either to the top or the bottom of your list.
