### ISSUE TITLE
keyboard event warning in RN0.27

### ISSUE THREAD

**Issue by evollu** [APSL/react-native-keyboard-aware-scroll-view#30]
getting `keyboardWillshow` event should be registered via the Keyboard module warning in RN 0.27.0

**Comment by alvaromb** [comment]
Will jump into this when I find some time. Thanks!

**Comment by deafben** [comment]
From v0.27.0 release :)

- Keyboard events should now be registered via Keyboard module:

```
// previously
const { DeviceEventEmitter } = require('react-native');
DeviceEventEmitter.addListener('keyboardWillShow', func);

// on 0.27.2 and newer
const { Keyboard } = require('react-native');
Keyboard.addListener('keyboardWillShow', func);

// 0.27.0 & 0.27.1
const Keyboard = require('Keyboard');
Keyboard.addListener('keyboardWillShow', func);
```

**Comment by alvaromb** [comment]
Closing by https://github.com/APSL/react-native-keyboard-aware-scroll-view/releases/tag/v0.1.2
