### ISSUE TITLE
Add onKeyboardWillShow to TypeScript types

### ISSUE THREAD

**Issue by karlvr** [APSL/react-native-keyboard-aware-scroll-view#306]
These methods appear to be missing from the TypeScript types file. I'm not actually sure which methods are supported! But it would be handy to have them there, e.g.

```
onKeyboardWillShow?: (frames: Object) => void
```

**Comment by yu629** [comment]
+1

**Comment by alvaromb** [comment]
@karlvr can you send us a PR?
