### ISSUE TITLE
Keyboard in scrollView creating extra space on top of views

### ISSUE THREAD

**Issue by clfristoe** [APSL/react-native-keyboard-aware-scroll-view#308]
When I tap the next or previous buttons, it scrolls as expected but when I tap the Done button or tap outside the keyboard, extra space appears at the top of the View (see video in zip file):
ExtraSpace.zip

The code:
`<ScreenRoot {...getCommonProps(this.props)} navigator={this.props.navigator} showFormNav={false} avoidKeyboard={false}>`
`<KeyboardScrollView>`
`<Form form={formName} ref={this.saveForm} onSubmit={this.handleSubmit} validate={validate} initialValues={this.initialValues} >`
`{this.props.currentUser.showDigitalDials === 'Yes' && <FormPicker title={'Contact Method'} name={'actualContactMethod'} items={actualContactMethodItems}/>}`
`<FormSwitch title={'New Set?'} name={'isNewSetCode'} />`
`<FormSwitch title={'Create Appointment?'} name={'createAppointment'} />`
`{appointmentComponents}`
`</Form>`
`</KeyboardScrollView>`
`<KeyboardAccessoryNavigation/>`
`</ScreenRoot>`

**Comment by nataly-chobat** [comment]
Hello @clfristoe! How have you solved your issue? I have the same behavior?
Help appreciated

**Comment by KristineTrona** [comment]
Having the same issue now, any suggestions?
