### ISSUE TITLE
undefined is not an object (evaluating 'frames.endCordinates.height') of react-native-keyboardevents

### ISSUE THREAD

**Issue by padraigobrien** [APSL/react-native-keyboard-aware-scroll-view#31]
When focusing on a textinput it throws the error. I tried fixing using the answer from http://stackoverflow.com/questions/32730736/undefined-is-not-an-object-evaluating-frames-end-height-of-react-native-keyb . the error disappeared but the scroll-view just does not work now.

Anyone else had this issue?

**Comment by alvaromb** [comment]
Hello! Which version are you running?

**Comment by alvaromb** [comment]
Hello @padraigobrien!

Please feel free to open any other issue if you need further help.
