### ISSUE TITLE
need props support for 'contentInset' of 'ScrollableComponent'

### ISSUE THREAD

**Issue by balchander** [APSL/react-native-keyboard-aware-scroll-view#311]
I'm using 'react-native-keyboard-aware-scroll-view' inside 'keyboard-aware-component'. 

When 'keyboardDidShow' event is triggered, 'keyboard-aware-component' is already handling the bottom padding. So I don't want the 'contentInset'  of 'react-native-keyboard-aware-scroll-view' to depend on 'keyboard-state'.

So I would suggest having a prop that would help in determining the contentInset.

**Comment by alvaromb** [comment]
Can you send us a PR?
