### ISSUE TITLE
Child components registering taps when scrolling

### ISSUE THREAD

**Issue by bsbechtel** [APSL/react-native-keyboard-aware-scroll-view#314]
I have a list of TextInputs inside a KeyboardAwareScrollView. I am seeing many situations where, when I start to scroll the list of inputs, the view does scroll, but then when I remove my finger, the TextInput is focused, causing the keyboard to display. I only want to focus on a TextInput when I tap. Do I need to put an eventDefault somewhere to prevent this behavior? At times, the onScroll event doesn't even seem to fire even though the view has started to scroll.

**Comment by alvaromb** [comment]
Can you test a regular scrollview with text input? This seems a RN upstream issue.

**Comment by bsbechtel** [comment]
@alvaromb  I'm sorry, I never saw the notification for your comment. I ended up using a Text component wrapped with a Touchable* component, and then just replace it with a TextInput component when the onPress is fired. I could never identify if this is specific to RN or this library, but it can be closed.
