### ISSUE TITLE
Extra empty space at bottom of screen on android

### ISSUE THREAD

**Issue by SunilPandey-** [APSL/react-native-keyboard-aware-scroll-view#346]
KeboardAwareScrollView created extra empty space at bottom of screen. but due to this topmost view is getting hidden 

any solution for this?

**Comment by getinfyKiranreddy** [comment]
you can just give css like flex:1 and and backGroundColor:'#ccc' to parent element 
then automatically it may cover the total screen

**Comment by SunilPandey-** [comment]
@getinfyKiranreddy  : Man Thanks :) Had given grand parent as flex : 1 and I was thinking it should solve. But you made my day.

Many Thanks

**Comment by renato-bvdash** [comment]
Did you mean the parent of `KeyboardAwareScrollview`? Mine already does and still has this extra space.

**Comment by Donhv** [comment]
issue happen both android & ios. set flex:1 not work for me.
