### ISSUE TITLE
  <KeyboardAwareScrollView> works as normal like <Scrollview>

### ISSUE THREAD

**Issue by susylPearl** [APSL/react-native-keyboard-aware-scroll-view#35]
this module works for me but intially when it renders it shows scrollbar, and behaves as like of scrollview. what is the purpose of behaving like scrollview? i only need scrolling view up when i input text in textfield. Give me some suggestion.

**Comment by alvaromb** [comment]
Hello @susylPearl!

I don't follow, this component is actually a `ScrollView` 😅. Maybe using `alwaysBounceHorizontal` and `alwaysBounceVertical` and setting both to `false` is what you need.

**Comment by susylPearl** [comment]
where should i use this? is this the properties of keyboardawarescrollview?

**Comment by alvaromb** [comment]
You can pass all `ScrollView` props to any `KeyboardAwareScrollView`.
