### ISSUE TITLE
Warning: ListView is deprecated and will be removed in a future release. See https://fb.me/nolistview for more information

### ISSUE THREAD

**Issue by vatex** [APSL/react-native-keyboard-aware-scroll-view#362]
Stack trace:
  node_modules\react-native\Libraries\YellowBox\YellowBox.js:59:8 in error
  node_modules\expo\build\environment\muteWarnings.fx.js:26:24 in error
  node_modules\react-native\node_modules\fbjs\lib\warning.js:30:18 in printWarning
  node_modules\react-native\node_modules\fbjs\lib\warning.js:51:23 in <unknown>
  node_modules\react-native\Libraries\Utilities\warnOnce.js:29:10 in warnOnce
  node_modules\react-native\Libraries\react-native\react-native-implementation.js:70:6 in ListView
  node_modules\react-native-keyboard-aware-scroll-view\lib\KeyboardAwareListView.js:6:38 in <unknown>
  node_modules\metro\src\lib\polyfills\require.js:331:6 in loadModuleImplementation
  node_modules\react-native-keyboard-aware-scroll-view\index.js:5:0 in <unknown>
  node_modules\metro\src\lib\polyfills\require.js:331:6 in loadModuleImplementation
  components\menu.js:25:0 in <unknown>
  node_modules\metro\src\lib\polyfills\require.js:331:6 in loadModuleImplementation
  App.js:21:0 in <unknown>
  node_modules\metro\src\lib\polyfills\require.js:331:6 in loadModuleImplementation
  node_modules\expo\AppEntry.js:4:0 in <unknown>
  node_modules\metro\src\lib\polyfills\require.js:331:6 in loadModuleImplementation
  node_modules\metro\src\lib\polyfills\require.js:197:45 in guardedLoadModule
  null:null in global code
  ...

"dependencies": {
    "expo": "33.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-keyboard-aware-scroll-view": "0.7.4",
    "react-native-web": "0.11.4",
    "react-navigation": "3.11.0"
  },

**Comment by Mxime** [comment]
updating `react-native-keyboard-aware-scroll-view` to `0.8.0` solve the problem  

https://github.com/APSL/react-native-keyboard-aware-scroll-view/releases/tag/v0.8.0
> Breaking: removed ListView (#319 (@ethanneff) and #327 @alvaromb)
