### ISSUE TITLE
[Android] when enableOnAndroid={true} and tap on TextInput it is opened FullScreen

### ISSUE THREAD

**Issue by alexei-sevrukov-topx** [APSL/react-native-keyboard-aware-scroll-view#368]
On ios it's working fine, but when I enable it on android I get this bug: TextInput is opened FullScreen but when I tap one letter TextInput is resized to normal size

React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 44.81 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 25, 28, 29
        Build Tools: 28.0.3, 29.0.0
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

Example:
![ezgif com-resize](https://user-images.githubusercontent.com/52152932/60428777-53203c80-9c02-11e9-96c4-e9399873a4fd.gif)

**Comment by keerthi0611** [comment]
This issue is already created and it is open....

**Comment by alexei-sevrukov-topx** [comment]
Ohhh, sorry, @keerthi0611 can you please send a link to this issue?

**Comment by keerthi0611** [comment]
> Ohhh, sorry, @keerthi0611 can you please send a link to this issue?

https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/333

**Comment by alexei-sevrukov-topx** [comment]
@keerthi0611 thank, so I close this issue because it's duplicate of [#333](https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/333)
