### ISSUE TITLE
Cannot read property 'addListener' of undefined

### ISSUE THREAD

**Issue by parthtiwari65** [APSL/react-native-keyboard-aware-scroll-view#37]
![simulator screen shot jun 23 2016 1 06 25 am](https://cloud.githubusercontent.com/assets/9299671/16295989/cf059b22-38de-11e6-8e50-c3f02dbb4336.png)

I am getting this error while trying to use the KeyboardAwareScrollView component.
It seems the 'Keyboard' keyword in Keyboard.addListener is not defined or not recognized.
Has anyone else faced the error?
Any help appreciated.

**Comment by parthtiwari65** [comment]
I made a change and submitted a merge request for this

**Comment by parthtiwari65** [comment]
It seems my solution only works for an older version of react-native. So please decline my pull request. Thanks

**Comment by alvaromb** [comment]
Hi @parthtiwari65!

Which version of RN are you using?

**Comment by parthtiwari65** [comment]
Hi @alvaromb , i have updated to the 0.27.2 now, and I am getting the error in the above image.
The componentDidMount,

```
  componentDidMount: function () {
    // Keyboard events
    this.keyboardWillShowEvent = Keyboard.addListener('keyboardWillShow', this.updateKeyboardSpace)
    this.keyboardWillHideEvent = Keyboard.addListener('keyboardWillHide', this.resetKeyboardSpace)
  },
```


throws the error. 

`Cannot read property of addListener`

**Comment by alvaromb** [comment]
Please update the library to the latest version, it will solve this error. 

Enviado desde mi iPhone

**Comment by parthtiwari65** [comment]
It is working after the update. Thanks!
