### ISSUE TITLE
FlatList - No scrollToIndex?

### ISSUE THREAD

**Issue by cristianoccazinsp** [APSL/react-native-keyboard-aware-scroll-view#372]
Getting undefined when calling scrollToIndex from the component.

**Comment by cristianoccazinsp** [comment]
Sorry, was using the wrong ref.

**Comment by ichiyouji** [comment]
@cristianoccazinsp could you please elaborate on how you solved this? thanks

**Comment by cristianoccazinsp** [comment]
I stopped using this library a while ago so I can't really recall what was the right way to obtain a ref to the original flat list, but it should be simple to debug and find it out!

**Comment by MountBaqer** [comment]
For whoever stumbles upon this in the future, I managed to solve this problem by doing this:

```typescript
const scrollRef = useRef<{ flatListRef: Element | undefined }>({ flatListRef: undefined });
...
(scrollRef.current?.flatListRef as any).scrollToIndex(); //scrollToIndex() works
...
<KeyboardAwareFlatList
            innerRef={(ref) => (scrollRef.current.flatListRef = ref)}
...
```

**Comment by mlthlschr** [comment]
Hi,

this approach does not work for me using class components. However, a different one does, namely by using [callback refs](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs).

**Comment by pbassi02** [comment]
Thanks mlthlschr,

Your solution worked for me in combination of using **innerRef**  prop of the keyboardAwareFlatlist

**Comment by zeusstl** [comment]
Thanks @MountBaqer. The `innerRef` solution worked wonders.

**Comment by omkar2737** [comment]
here is the modified file [KeyboardAwareHOC.js] (https://github.com/user-attachments/files/22091248/KeyboardAwareHOC.js)

Just modify node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js file

scrollToIndex = (params: {
  animated?: boolean,
  index: number,
  viewOffset?: number,
  viewPosition?: number
}) => {
  if (this._rnkasv_keyboardView && this._rnkasv_keyboardView.scrollToIndex) {
    this._rnkasv_keyboardView.scrollToIndex(params)
  } else {
    console.warn("scrollToIndex is only available on FlatList");
  }
}


<ScrollableComponent
  {...refProps}
  ...
  scrollIntoView={this.scrollIntoView}
  scrollToIndex={this.scrollToIndex}   // ✅ new
  scrollToEnd={this.scrollToEnd}
  scrollToPosition={this.scrollToPosition}
/>
