### ISSUE TITLE
ListView has been removed  (RN 0.60+)

### ISSUE THREAD

**Issue by Aleksandern** [APSL/react-native-keyboard-aware-scroll-view#375]
There is error if you use Ract-Native 0.60+

>ListView has been removed from React Native. See https://fb.me/nolistview for more information or use `deprecated-react-native-listview'

**Comment by Pardhasaradhi6777** [comment]
Same issue, 

> There is error if you use Ract-Native 0.60+
> 
> > ListView has been removed from React Native. See https://fb.me/nolistview for more information or use `deprecated-react-native-listview'

May I know how did you solved it, Please
Thanks
