### ISSUE TITLE
Only scroll to view when view is hidden under keyboard

### ISSUE THREAD

**Issue by Andreyco** [APSL/react-native-keyboard-aware-scroll-view#39]
See the attachment. Such handling looks messy and should not happen.

![unnecessary-scroll](https://cloud.githubusercontent.com/assets/829963/16356557/bea9a99e-3adc-11e6-9e09-131f55486eb6.gif)

**Comment by alvaromb** [comment]
Hello @Andreyco!

Do you feel you can send a PR for that? We're a bit overwhelmed here and we cannot jump into this at this moment.

**Comment by Andreyco** [comment]
I think so... Give me a few days...

**Comment by alvaromb** [comment]
Any updates on this, @Andreyco?

**Comment by alvaromb** [comment]
Published v0.2.1 with #67
