### ISSUE TITLE
scrollToFocusedInput in functional component

### ISSUE THREAD

**Issue by jjg77** [APSL/react-native-keyboard-aware-scroll-view#397]
Does anyone have an example of how to implement the scrollToFocusedInput in a functional component with hooks (no classes).  Thanks

**Comment by gamingumar** [comment]
@jjg77 I want to scroll to top, but not working for me. Have you had any luck?

**Comment by jjg77** [comment]
Yes, I did something like this.  You place this function with your flatlist and pass it as a prop to the items.

```
const _scrollToIndex = index => {
    //console.log('called _scrollToIndex: ', index);
    if (index <= comments.length && index >= 0){
      flatListRef.current.scrollToIndex({animated: true, index: index})
    }else{
      console.log('index out of range, scroll to bottom');
      flatListRef.current.scrollToIndex({animated: true, index: comments.length-1})
    }
  }
```

**Comment by gamingumar** [comment]
I am using react hooks and I am assigning ref like this.

```
let listRef = useRef();
const _scrollToTop = () => {
listRef.current.scrollToIndex({animated: true, index: 0})
}


<KeyboardAwareFlatList
          innerRef={r => (listRef = r)}
/>


```
I have also tried 
``` listRef.props.scrollToPosition(0, 0) ```

Both of these don't work and listRef.current throws undefined error.

**Comment by Nextt1** [comment]
@jjg77 how are assigning the ref? I'm getting null or undefined ref value.

**Comment by DanyylCodeGenerationSoftware** [comment]
const _scrollToTop = () => {
listRef?.current?.scrollToPosition(0,0)
}

**Comment by hamzaabujarad** [comment]
use ` innerRef={(ref) => scrollRef.current = ref}`
 instead of  `  innerRef={r => (listRef = r)}`

**Comment by alainib** [comment]
> use ` innerRef={(ref) => scrollRef.current = ref}` instead of ` innerRef={r => (listRef = r)}`

where come from the `scrollRef` please ?
