### ISSUE TITLE
scrollIntoView not working on android

### ISSUE THREAD

**Issue by Donhv** [APSL/react-native-keyboard-aware-scroll-view#407]
Pls Help!
function scrollIntoView(myRef) working perfect on iOS. But on Android, scrollview always scroll to Top.
react-native v0.59.9

**Comment by Donhv** [comment]
ahh I fixed it according to
https://github.com/facebook/react-native/issues/12966

**Comment by alexyangjie** [comment]
> ahh I fixed it according to
> [facebook/react-native#12966](https://github.com/facebook/react-native/issues/12966)

Hi, I am running into the exact same issue as you. Could you please share how you fix it? In the issue you mentioned there are multiple ways to address this, but none of them work in my case.

**Comment by michaelcsilva** [comment]
I see the same issue w/ React native 0.64.2
