### ISSUE TITLE
Malformed calls from JS : field Sizes are different

### ISSUE THREAD

**Issue by MayoudP** [APSL/react-native-keyboard-aware-scroll-view#415]
Hello,
I have a JSON array structured more or less like that : 
```
[
    {
       label: "Can you upload a photo of a document?",
       id: 0
    },
    {
       label: "Can you upload a photo of a second ID document?",
       id: 1
    },
    ...
]
```

If I'm using a simple FlatList to render the item's array, such like that for example : 
  ```
 <FlatList
        data={signUpPreciseInfos}
        renderItem={({ item }) => this.renderScene(item)}
        keyExtractor={item => item.id}/>
```
It's working well, however, if I'm using `KeyboardAwareFlatList` : 

  ```
   <KeyboardAwareFlatList
                    enableOnAndroid={true}
                    innerRef={item => { this.scroll = item }}
                    getItemLayout={(data, index) => ({ length: 90, index })}
                    data={signUpPreciseInfos}
                    contentContainerStyle={{ marginHorizontal: Metrics.horizontalPadding }}
                    ref={(item) => this.flatList = item}
                    renderItem={({ item }) => this.renderScene(item)}
                    keyExtractor={item => item.id}
                />
```
it's throwing this screen : 
<img src="https://user-images.githubusercontent.com/48682041/71732325-3ed62a00-2e47-11ea-9b70-3963fe4bdb81.png" width="200" height="400" />

Can't figure it why it's doing that. **BUT** ⚠️very important ⚠️`KeyboardAwareFlatList` is actually **WORKING** if I set the length of the array to 10 items max. If I'm adding  more that 10 items, then the error occured...

Any ideas why it's doing that ? 

Thanks for the help

**Comment by faz919** [comment]
^ same question, i'm having this problem too. insane that 2 years later it's still an issue
