### ISSUE TITLE
Don't break API on minor versions

### ISSUE THREAD

**Issue by explorigin** [APSL/react-native-keyboard-aware-scroll-view#42]
Before I complain a bit. Thanks for this. It solved a need that I had.  Now, on to my mild rant.

I reloaded my node_modules with my dependency set at `"react-native-keyboard-aware-scroll-view": "~0.1.0",` to allow non-breaking changes (according to semantic versioning).

This upgraded me from 0.1.0 to 0.1.2.  Now KASV _requires_ React Native 0.27.  This is a breaking change and should be reserved for a 0.2.0 release.  For now, I'll just fix my `package.json` but you should try to avoid this situation in order to be producing a quality reusable component.

**Comment by alvaromb** [comment]
You're completely right @explorigin, my fault!

I will bump the version number in a major way any time a RN update is required.

**Comment by alvaromb** [comment]
Closing this, thanks for the comment @explorigin! Sorry 😿 👍
