### ISSUE TITLE
there should be a prop that disables scroll when keyboard hid.

### ISSUE THREAD

**Issue by onurcskun** [APSL/react-native-keyboard-aware-scroll-view#420]
I want a fixed screen without scroll even if it reset back. just push them up when the keyboard showed up.

Or anyone can tell me how can I make it myself

-----------------------

I added Keyboards listeners and i succeded.

**Comment by mikerodham** [comment]
@onurcskun Can you explain what you did to fix this? Having the same problem, am I overwriting the keyboard or listening for keyboard will close then disabling scroll of the scrollview? What do you think's best?
