### ISSUE TITLE
Allow extra height to be set via props

### ISSUE THREAD

**Issue by MovingGifts** [APSL/react-native-keyboard-aware-scroll-view#43]
In the KeyboardAwareMixin.js `const _KAM_EXTRA_HEIGHT = 75` is the default.
It is hardcoded and we have to manually change the extra height there, but will break with a new upgrade. Is there a way you can allow to set it via props? Something like this:
`<KeyboardAwareScrollView extraHeight={120}`?

**Comment by JosephDev** [comment]
you can pass extraHeight as props. I tested it just and it works as your needs. 
version. 0.1.2

**Comment by MovingGifts** [comment]
Works like magic, thanks for pointing it out!
