### ISSUE TITLE
version 0.9.2

### ISSUE THREAD

**Issue by eae-christian** [APSL/react-native-keyboard-aware-scroll-view#444]
Hi
I'm seeing Latest 0.9.2 in the list of releases but when I try to install it I get an npm error, do I have to change something on my side?

npm ERR! notarget No matching version found for react-native-keyboard-aware-scroll-view@^0.9.2.

Thanks

**Comment by rborn** [comment]
Not published yet,  I'm waiting for the repo owner to do it :(
