### ISSUE TITLE
No matching version found for react-native-keyboard-aware-scroll-view@0.9.2

### ISSUE THREAD

**Issue by imceZZ** [APSL/react-native-keyboard-aware-scroll-view#445]
I'm trying to install the latest version but i get this error in terminal **No matching version found for react-native-keyboard-aware-scroll-view@0.9.2.**

this is probably from NPM because you haven't published yet this version on NPM, can you publish it.

**Comment by rborn** [comment]
https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/443#issuecomment-659357780
