### ISSUE TITLE
After focused, ScrollView has margin status bar

### ISSUE THREAD

**Issue by JosephDev** [APSL/react-native-keyboard-aware-scroll-view#45]
![out](https://cloud.githubusercontent.com/assets/7818008/16607686/f28bcfde-42f8-11e6-9cd5-c4cee9b641ac.gif)

as you can see, after focusing an InputText, ScrollView has margin on top as much as status bar.

**Comment by MovingGifts** [comment]
@JosephDev I had the same issue for top and bottom, I added this prop seemed to work `<KeyboardAwareScrollView contentInset={{bottom: 0}}` didn't seem to break anything for me..

**Comment by JosephDev** [comment]
Thank you for your comment.
I tried it, but no lucks to me :(

**Comment by alvaromb** [comment]
Hello @JosephDev!

Can you post your source code so I can test it?

**Comment by alvaromb** [comment]
Any news @JosephDev?

**Comment by JosephDev** [comment]
@alvaromb sorry for late response. As @MovingGifts mention, with it works with `contentInset={{bottom: 0}}` however, it doesn't help on sub-pages and `_KAM_EXTRA_HEIGHT` option also has a problem. I will create a mock-up project and test those two with sub-pages and update my code as soon as possible.

**Comment by JosephDev** [comment]
I created a clean sample project just to test.
@MovingGifts 's solution is working with sub-pages.
I think it was not working because of another dependencies.

here is my packages to generate a sample project. 

```
"react": "15.2.1",
"react-native": "0.29.2",
"react-native-keyboard-aware-scroll-view": "git://github.com/JosephDev/react-native-keyboard-aware-scroll-view.git#ancestor_check",
"react-native-router-flux": "^3.31.2"
```

**Comment by alvaromb** [comment]
Cool @JosephDev!

Let me know if I can help you with anything else ☺️

**Comment by ronaldheft** [comment]
For anyone that runs into this in the future, this can be fixed with the prop:

`automaticallyAdjustContentInsets={false}`

Using the `contentInset` prop will cause issues if you scroll the view with the keyboard open.

**Comment by hejiaji** [comment]
@ronaldheft It really helps, thanks man
