### ISSUE TITLE
AutoFocus not working

### ISSUE THREAD

**Issue by vaibhawc** [APSL/react-native-keyboard-aware-scroll-view#46]
It doesn't seem to work in 0.1.2.
When I set `alwaysBounceHorizontal` & `alwaysBounceVertical` as `false`, as in #35 (I faced the same issue),
it wouldn't autofocus, and when I manually scroll to the desired TextInput and dismiss the keyboard the scrollView is stuck at its position.
Is there a guideline or things to keep in mind with this? Most of the textinputs are hidden behind the keyboard in my case.

**Comment by alvaromb** [comment]
Are you using the component in Android, @vaibhawc?

Sorry, currently in family vacation with very bad 📶

**Comment by alvaromb** [comment]
Any news @vaibhawc?

**Comment by vaibhawc** [comment]
Sorry @alvaromb, even I was in some family thing. I am using it in iOS RN 0.27.
I thought too much but since I am naive to both RN and iOS, I couldn't make it to work.
In hurry, I chose to use another library. But even that doesn't quite pacify me.
Once I am done with the first release I will again visit this issue. May be by then I can have enough know-how to look into the codes, understand, suggest and edit them.
Btw, Thanks for your sincerity and effort man.

**Comment by alvaromb** [comment]
Ok!

Please let me know if I can help you with something. Closing by now, feel free to ping me and I'll reopen 😉
