### ISSUE TITLE
Position not quite right

### ISSUE THREAD

**Issue by npomfret** [APSL/react-native-keyboard-aware-scroll-view#47]
It looks like the keyboard isn't positioned quite right - it overlaps the text input.  

![screen shot 2016-07-18 at 12 32 21](https://cloud.githubusercontent.com/assets/5489469/16913645/d3db6474-4ce3-11e6-8e1d-a05dbb038ad0.png)

I _think_ it changed after upgrading to RN 0.29

**Comment by alvaromb** [comment]
You can set the `extraHeight` prop as a workaround. Will test this tomorrow, thanks for the report.

**Comment by alvaromb** [comment]
Please use `extraHeight` to adjust the position of the keyboard.

**Comment by npomfret** [comment]
Add extraHeight to what?  Adding it as a prop to the KeyboardAwareScrollView didn't work.  Tried both `extraHeight={50}` & `extraHeight={-50}`.  In fact it seemed to make it worse, in that the view I want to see is even more hidden that it was without the extraHeight.

**Comment by alvaromb** [comment]
Set an `extraHeight` prop of `100` with the latest library version. Usually this happens when you have a `TabBar` but the component doesn't know it (there's another prop to tell the component it is living inside a `TabBar`, see https://github.com/APSL/react-native-keyboard-aware-scroll-view#props

**Comment by npomfret** [comment]
Ok, thanks very much!

**Comment by alvaromb** [comment]
Let me know if that worked @npomfret ! 👍

**Comment by npomfret** [comment]
It worked, thanks.
