### ISSUE TITLE
Not working with Navigator

### ISSUE THREAD

**Issue by nicoecheza** [APSL/react-native-keyboard-aware-scroll-view#49]
We tested this component with and without the RN Navigator component, and when we use it with the Navigator as a wrapper to all our views, the keyboard-aware stops working.
We are working on Android.
Any thoughts on this?

**Comment by alvaromb** [comment]
I've successfully used this component with `Navigator`. Can you check what's the Android version you're testing on?

**Comment by alvaromb** [comment]
Closing. Please let me know if you need further help.
