### ISSUE TITLE
library will crash on react native 0.65.0

### ISSUE THREAD

**Issue by husseinAbdulnabi** [APSL/react-native-keyboard-aware-scroll-view#494]
since this [099f67cf8a](https://github.com/facebook/react-native/commit/099f67cf8aa290592092cfa0cb4e938d0543b696) has been added to react native 0.65.0, the library will crash when trying to call `scrollResponderScrollTo` or `scrollResponderScrollToEnd`, I've solved it by changing these functions to `scrollTo` and `scrollToEnd`, please solve this ASAP because many users will be affected by that change in the upcoming version of react native.

**Comment by alvaromb** [comment]
Mind to send a PR?

**Comment by thomasdittmar** [comment]
I can confirm that this library breaks with this setup:

```
"react": "17.0.2",
"react-native": "0.65.0-rc.3",
"react-native-keyboard-aware-scroll-view": "^0.9.4",
```

Screenshot of error:

<img src="https://user-images.githubusercontent.com/75284636/129155883-98623e86-f351-46b7-9445-5a75c5d7bd29.png" title="GIF of the app" width="300"  />

**Comment by h0nor** [comment]
> since this [099f67cf8a](https://github.com/facebook/react-native/commit/099f67cf8aa290592092cfa0cb4e938d0543b696) has been added to react native 0.65.0, the library will crash when trying to call `scrollResponderScrollTo` or `scrollResponderScrollToEnd`, I've solved it by changing these functions to `scrollTo` and `scrollToEnd`, please solve this ASAP because many users will be affected by that change in the upcoming version of react native.

@husseinAbdulnabi where did you make these changes exactly? KeyboardAwareHOC.js?

Like below?

`scrollToPosition = (x: number, y: number, animated: boolean = true) => {
      const responder = this.getScrollResponder()
      responder && responder.scrollTo({ x, y, animated })
    }

    scrollToEnd = (animated?: boolean = true) => {
      const responder = this.getScrollResponder()
      responder && responder.scrollToEnd({ animated })
    }`

**Comment by husseinAbdulnabi** [comment]
@h0nor check this https://github.com/husseinAbdulnabi/react-native-keyboard-aware-scroll-view/commit/e66c4a62fde8295ab511d086d0d59ef3247a5225

**Comment by h0nor** [comment]
Yeah, these changes seem to work. To solve the problem in my previous attempt, I changed `scrollReponderScrollTo` method with `scrollToPositon` method, and that change produced the same "**is not a function**" error. But changing `scrollReponderScrollTo` to `scrollTo` did not create any exceptions. Do you know why? @husseinAbdulnabi

**Comment by h0nor** [comment]
@thomasdittmar do you think the package will keep working as expected with your change below?

scrollToPosition = (x: number, y: number, animated: boolean = true) => {
  const responder = this.getScrollResponder()
  responder && responder.scrollResponderScrollTo && responder.scrollResponderScrollTo({ x, y, animated })
}

I feel like you might avoid the exception but the component may not work as expected. Maybe changing the method names will keep the component working as expected? like @husseinAbdulnabi proposed...

**Comment by thomasdittmar** [comment]
@h0nor Yes it will. 

I have temporarily copied all the files into my project folder, with this change and including the `index.js, and it works.

Keeping in mind I don't invoke any of the `scrollTo*` function as I don't need them.

**Comment by mhammerc** [comment]
If anyone need it while waiting for an official release, here is the patch from husseinAbdulnabi@e66c4a6 that can be used with `patch-package`.

filename `react-native-keyboard-aware-scroll-view+0.9.4.patch`

```patch
From e66c4a62fde8295ab511d086d0d59ef3247a5225 Mon Sep 17 00:00:00 2001
From: hussein abdulnabi <husseinabdulnabi@husseins-MacBook-Pro-2.local>
Date: Sun, 27 Jun 2021 19:20:15 +0300
Subject: [PATCH] fixes scroll responder on rn 0.65.0

---
 lib/KeyboardAwareHOC.js | 10 +++++-----
 1 file changed, 5 insertions(+), 5 deletions(-)

diff --git a/node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js b/node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js
index 3d94b82..bb273ee 100644
--- a/node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js
+++ b/node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js
@@ -273,12 +273,12 @@ function KeyboardAwareHOC(
 
     scrollToPosition = (x: number, y: number, animated: boolean = true) => {
       const responder = this.getScrollResponder()
-      responder && responder.scrollResponderScrollTo({ x, y, animated })
+      responder && responder.scrollTo({ x, y, animated })
     }
 
     scrollToEnd = (animated?: boolean = true) => {
       const responder = this.getScrollResponder()
-      responder && responder.scrollResponderScrollToEnd({ animated })
+      responder && responder.scrollToEnd({ animated })
     }
 
     scrollForExtraHeightOnAndroid = (extraHeight: number) => {
```

This fix seem to work on my app.

**Comment by jacargentina** [comment]
@alvaromb  can you look at this please?

**Comment by julianklumpers** [comment]
i can confirm we have the same issue when we upgrade to `react-native` version `0.65.1`

![IMG_1477](https://user-images.githubusercontent.com/26057014/130295576-dab30b9c-e37a-4359-ab6c-380357e77dfb.jpeg)

**Comment by srmagura** [comment]
If you use NativeBase, you also need to patch this in `@codler/react-native-keyboard-aware-scroll-view`.

**Comment by jacargentina** [comment]
@srmagura  nativebase v2 only; v3 dropped that dependecy

**Comment by IljaDaderko** [comment]
Just came across this as well, do you guys know when the fix will b available on npm?

**Comment by dishantwalia** [comment]
> If anyone need it while waiting for an official release, here is the patch from [husseinAbdulnabi/react-native-keyboard-aware-scroll-view@e66c4a6](https://github.com/husseinAbdulnabi/react-native-keyboard-aware-scroll-view/commit/e66c4a6) that can be used with `patch-package` (https://www.npmjs.com/package/patch-package).
> 
> filename `react-native-keyboard-aware-scroll-view+0.9.4.patch`
> 
> ```diff
> From e66c4a62fde8295ab511d086d0d59ef3247a5225 Mon Sep 17 00:00:00 2001
> From: hussein abdulnabi <husseinabdulnabi@husseins-MacBook-Pro-2.local>
> Date: Sun, 27 Jun 2021 19:20:15 +0300
> Subject: [PATCH] fixes scroll responder on rn 0.65.0
> 
> ---
>  lib/KeyboardAwareHOC.js | 10 +++++-----
>  1 file changed, 5 insertions(+), 5 deletions(-)
> 
> diff --git a/node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js b/node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js
> index 3d94b82..bb273ee 100644
> --- a/node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js
> +++ b/node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js
> @@ -273,12 +273,12 @@ function KeyboardAwareHOC(
>  
>      scrollToPosition = (x: number, y: number, animated: boolean = true) => {
>        const responder = this.getScrollResponder()
> -      responder && responder.scrollResponderScrollTo({ x, y, animated })
> +      responder && responder.scrollTo({ x, y, animated })
>      }
>  
>      scrollToEnd = (animated?: boolean = true) => {
>        const responder = this.getScrollResponder()
> -      responder && responder.scrollResponderScrollToEnd({ animated })
> +      responder && responder.scrollToEnd({ animated })
>      }
>  
>      scrollForExtraHeightOnAndroid = (extraHeight: number) => {
> ```
> 
> This fix seem to work on my app.

+1 Working fine

**Comment by oliverdolgener** [comment]
https://github.com/APSL/react-native-keyboard-aware-scroll-view/pull/501

**Comment by dongdyang** [comment]
try this one `    "react-native-keyboard-aware-scroll-view": "github:APSL/react-native-keyboard-aware-scroll-view#pull/501/head",
`

**Comment by karladler** [comment]
when will the fix be released?

**Comment by lfoliveir4** [comment]
I'm using this library and updated my React Native to 0.66.1 and the error still persists! Any suggestions for a solution?

**Comment by KashyapKarkar** [comment]
@lfoliveir4  
change this in your package.json 
"react-native-keyboard-aware-scroll-view": "github:APSL/react-native-keyboard-aware-scroll-view#pull/501/head",

npm install in project directory  and run project

**Comment by vinayr** [comment]
for yarn
```
yarn add APSL/react-native-keyboard-aware-scroll-view#501/head
```
