### ISSUE TITLE
Android | KeyboardAwareScrollView overlaps react-navigation header & statusbar

### ISSUE THREAD

**Issue by oguzturker8** [APSL/react-native-keyboard-aware-scroll-view#497]
Hi, I'dont thing its the right behavior. KeyboardAwareScrollView overlaps custom header and statusbar when text input is focused.
I can avoid overlapping the statusbar when i set backgroundColor not transparent but i need to do it.

**Navigation no custom codes.**

_Stack.Navigator
Screen 
Stack.Navigator_

**Screen**

_Container
...
TextInput 
TextInput 
TextInput 
...
Container_ 

**Container**

_SafeAreaView
StatusBar backgroundColor='transparent'
KeyboardAwareScrollView>
{children}
KeyboardAwareScrollView 
SafeAreaView_ 

And i set <activity android:name=".MainActivity" ... android:windowSoftInputMode="adjustPan"  ...   />

transparent statusbar
<img src="https://user-images.githubusercontent.com/33129613/128323405-2795b93c-2278-4412-bca8-bfd014076463.gif" width="400" height="800">

not transparent
<img src="https://user-images.githubusercontent.com/33129613/128323587-b930bf62-2206-4003-b817-b9f94925530a.gif" width="400" height="800">

**Comment by oguzturker8** [comment]
Swaggy_McMuffin's [solution](https://www.reddit.com/r/reactnative/comments/oz3vq0/help_keyboardawarescrollview_pushes_up_custom/h7ygrhh?utm_source=share&utm_medium=web2x&context=3) works.
_This has nothing to do with KeyboardAwareScrollView and everything to do with your activity android:windowSoftInputMode being "adjustPan". Change it to "adjustResize" and make sure to recompile the apk - aka npx react-native run-android._

**Comment by litinskii** [comment]
<img width="856" alt="image" src="https://github.com/APSL/react-native-keyboard-aware-scroll-view/assets/10028441/d3d347fd-7dd4-44d9-913d-b817955b01f8">
have the same issue with adjustPan as doc mention

**Comment by denisha25** [comment]
still getting same issue in android devices
When I click on textinput then my custom header scroll to up and overlap 
my react native and keyboardAwareScrollview library version 
"react-native-keyboard-aware-scroll-view": "^0.9.5",
 "react-native": "0.73.6",
