### ISSUE TITLE
Scroll view doesn't scroll when input is focused.

### ISSUE THREAD

**Issue by 5amfung** [APSL/react-native-keyboard-aware-scroll-view#5]
I have multiple inputs structured like the following, when I tap and focus on an input close to the bottom, I expect the view to scroll to the focused input because the input is underneath the keyboard.  But the scroll view doesn't do anything.  Am I missing something here?  Do I need to call anything from ```onFocus``` of each ```<TextInput>```?

```
    <KeyboardAwareScrollView viewIsInsideTabBar={true}
                                     keyboardShouldPersistTaps={true}>
            <View>
                <View>
                    <TextInput>...</TextInput>
                </View>
                <View>
                    <TextInput>...</TextInput>
                </View>
                <View>
                    <TextInput>...</TextInput>
                </View>
            </View>
    </KeyboardAwareScrollView>
```

**Comment by alvaromb** [comment]
Hello @5amfung!

Sadly this component doesn't scroll automatically, only resizes the `ScrollView` when the keyboard appears. But you can actually do it (I think I should provide some mechanism to do it easily, will think about that), take this example as a reference https://github.com/facebook/react-native/issues/3195#issuecomment-146518331.

In that comment, I explain how you can use the `scrollToFocusedInput` method of this library to auto-scroll when an input gets focused.

Please let me know if you need more information.

**Comment by 5amfung** [comment]
@alvaromb Thanks for the reply.  I ended doing something like this:

```
    <TextInput ref='foo' onFocus={(event) => {
        this._handleFocus(event, 'foo');
    }}/>
```

```
    _handleFocus(event, refName) {
        let node = React.findNodeHandle(this.refs[refName]);
        let extraHeight = 100;
        this.refs.keyboardAwareScrollView.scrollToFocusedInput(event, node, extraHeight);
    }
```

**Comment by alvaromb** [comment]
Happy to have helped!

Will try to do this more easily in next releases :)

**Comment by HighSoftWare96** [comment]
> @alvaromb Thanks for the reply. I ended up doing something like this:
> 
> ```
>     <TextInput ref='foo' onFocus={(event) => {
>         this._handleFocus(event, 'foo');
>     }}/>
> ```
> ```
>     _handleFocus(event, refName) {
>         let node = React.findNodeHandle(this.refs[refName]);
>         let extraHeight = 100;
>         this.refs.keyboardAwareScrollView.scrollToFocusedInput(event, node, extraHeight);
>     }
> ```

I'm getting this error...
![screen shot 2018-10-12 at 12 52 14](https://user-images.githubusercontent.com/22793967/46865433-d05e1400-ce1d-11e8-9619-16ac597b5178.png)

This the focus handler code: 
```
    const node = ReactNative.findNodeHandle(event.target);
    const extraHeight = 100;
    this.refs.scroll.scrollToFocusedInput(event, node, 100);
```
