### ISSUE TITLE
crash since upgrade to RN 0.65.1

### ISSUE THREAD

**Issue by Jackmekiss** [APSL/react-native-keyboard-aware-scroll-view#505]
The library crash since I upgraded react native to 0.65.1. 
But it's not the same crash reported already, I tested this fix https://github.com/APSL/react-native-keyboard-aware-scroll-view/pull/501 but it's not working.

[
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-31 at 10 16 14](https://user-images.githubusercontent.com/37016361/131467859-a3f9c70b-d770-485c-b69b-fb7cde9d5c37.png)
](url)

Someone has the same crash ?

**Comment by dioncodes** [comment]
I had the same issue but this patch fixed it for me: https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/494#issuecomment-904518711

**Comment by agusmao** [comment]
Did you get to fix your problem? With hermes enabled I see the same error as the picture, and with it disabled, I see the `responder.scrollResponderScrollTo` error. But even after patching the error persists for me.

**Comment by HZHAIX** [comment]
RN release discussion has mentioned this : https://github.com/react-native-community/releases/issues/242#issuecomment-900132372, hope can be fixed soon.

**Comment by dongdyang** [comment]
try this one `    "react-native-keyboard-aware-scroll-view": "github:APSL/react-native-keyboard-aware-scroll-view#pull/501/head",
`

**Comment by longb1997** [comment]
@ddongdyang, thanks for that. I will try it.
Please remind me when this lib fix it.
