### ISSUE TITLE
TypeError: responder.scrollResponderScrollTo is not a function. (In 'responder.scrollResponderScrollTo

### ISSUE THREAD

**Issue by AvitaliyaORG** [APSL/react-native-keyboard-aware-scroll-view#508]
When I tried to `KeyboardAwareScrollView` with `TextInput` 
![simulator_screenshot_E4C3359A-1C46-4A34-8299-6F052D9DC3A6](https://user-images.githubusercontent.com/54949248/133787535-c1f229d7-3e84-4986-9914-c49f6d864317.png)

**Comment by AvitaliyaORG** [comment]
I have found a temporary solution. add this in `package.json` file

`"react-native-keyboard-aware-scroll-view": "github:APSL/react-native-keyboard-aware-scroll-view#pull/501/head",`

**Comment by ksielyov** [comment]
Why I should use it? Is this a bug in a library and we should to wait update?

**Comment by ramsesDeco** [comment]
yes @ksielyov , there is a bug for RN v0.65.*, you shouldn't wait since the bug has been there for at least for 1 month, I really dont know why they don't fix it, but I will share you another solution, using patch-package, https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/494#issuecomment-900089166

**Comment by dariuxmx** [comment]
In my case, I resolved using these props:
```
<KeyboardAwareScrollView
  enableOnAndroid={true}
  keyboardShouldPersistTaps={"handled"}
  enableResetScrollToCoords={false}
  >
```

**Comment by barmola** [comment]
Thankyou @dariuxmx it worked for me

> In my case, I resolved using these props:
> 
> ```
> <KeyboardAwareScrollView
>   enableOnAndroid={true}
>   keyboardShouldPersistTaps={"handled"}
>   enableResetScrollToCoords={false}
>   >
> ```

**Comment by geroale** [comment]
Same issue here

**Comment by mitjnextt** [comment]
I have not used react-native-keyboard-aware-scroll-view, even though I'm getting this error, any luck?

**Comment by n10ty** [comment]
> I have not used react-native-keyboard-aware-scroll-view, even though I'm getting this error, any luck?

Probably, you using some other component, that depends on react-native-keyboard-aware-scroll-view. Try to search in node_modules.

**Comment by karladler** [comment]
> > I have not used react-native-keyboard-aware-scroll-view, even though I'm getting this error, any luck?
> 
> Probably, you using some other component, that depends on react-native-keyboard-aware-scroll-view. Try to search in node_modules.

try:

$ yarn why react-native-keyboard-aware-scroll-view

**Comment by anboia** [comment]
> yes @ksielyov , there is a bug for RN v0.65.*, you shouldn't wait since the bug has been there for at least for 1 month, I really dont know why they don't fix it, but I will share you another solution, using patch-package, [#494 (comment)](https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/494#issuecomment-900089166)

same issue https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/494 https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/504 https://github.com/APSL/react-native-keyboard-aware-scroll-view/pull/501

**Comment by janet-rivas** [comment]
> > I have found a temporary solution. add this in `package.json` file
> > `"react-native-keyboard-aware-scroll-view": "github:APSL/react-native-keyboard-aware-scroll-view#pull/501/head",`
> 
> This worked for me, I added a line to package.json and ran a 'yarn' command to install over the other version.

I have the same issue in RN 0.66 This work and this work
