### ISSUE TITLE
Keyboard Push View 

### ISSUE THREAD

**Issue by filippobarcellos** [APSL/react-native-keyboard-aware-scroll-view#535]
Hi. First of all thank you for the lib, it's really awesome. I'm having some problems trying to make the bottom sheet to respond based on the size of the content. My bottom sheet needs to have a fixed input on the bottom and 2 positions - 50% and 90%. On 50% the bottom sheet needs to be pushed when the keyboard appears and on 90% the content of my flat list needs to be pushed up. Is possible to achieve this? 

 ![Untitled-2022-04-23-0039](https://user-images.githubusercontent.com/56128203/164841541-7f5e4b08-7d29-4ef5-91f9-f24f9c63d1e9.png)

## Steps To Achieve

1. On 50% - bottom sheet needs to be pushed up until the max size(90%)
2. on 90% - the flat list inside needs to be pushed up

**Comment by phamtien1709** [comment]
@filippobarcellos sorry to bother. Have you found a solution yet?

**Comment by filippobarcellos** [comment]
I haven't. I ended up using another library. If you want I could share a gist.

**Comment by phamtien1709** [comment]
@filippobarcellos Could you please give me a hint on changing your library to achieve it? 👯

**Comment by Yiin** [comment]
> I haven't. I ended up using another library. If you want I could share a gist.

What library did you ended up using?
