### ISSUE TITLE
scrollTo method is undefined

### ISSUE THREAD

**Issue by hasanalicansu** [APSL/react-native-keyboard-aware-scroll-view#544]
scrollTo method is undefined at KeyboardAwareScrollView
<img width="216" alt="image" src="https://user-images.githubusercontent.com/63130177/174259628-1ad5feee-1e01-43c5-9e50-89b26bb658c4.png">

```
 const scrollRef = useRef();

 console.log(' scrollRef.scrollTo', scrollRef.current?.scrollTo);

//*******

 <KeyboardAwareScrollView ref={scrollRef} {...scrollViewProps} style={[{ flex: 1 }, containerStyle]} showsVerticalScrollIndicator={false}>
              {children}
</KeyboardAwareScrollView>
```

**Comment by hasanalicansu** [comment]
I found one solutions for scrollTo,

I used `scrollRef.current?.scrollToPosition(0, 0, true)` instead of scrollTo for auto scroll to top

**scrollToPosition: (x: number, y: number, animated?: boolean) => void**

**Comment by GwFreak01** [comment]
@hasanalicansu how did you make it work for Android? Any extra configs?

**Comment by hasanalicansu** [comment]
@GwFreak01 hi mate, I'm sorry for the delay.

I have used "useScrollToTop" from '@react-navigation/native' for this feature. When user press the bottom tab icon, page scrolling to top of page like twitter app. 

This is my code, When user press the bottom tab icon, **useScrollToTop** hooks run and page scrolling to top of page

```
export const Layout = ({ children, colorScheme, containerStyle, backgroundColor = colorScheme.background, statusBarColor, ...scrollViewProps }) => {
  const scrollRef = useRef(null);

  useScrollToTop(React.useRef({
    scrollToTop: () => scrollRef.current?.scrollToPosition && scrollRef.current?.scrollToPosition(0, 0, true),
  }));

 return (
    <View style={{ flex: 1, backgroundColor }}>
      <StatusBar translucent backgroundColor={statusBarColor || colorScheme.statusBar} />
      <KeyboardAwareScrollView ref={scrollRef}> {children} </KeyboardAwareScrollView>
    </View>
  );
};
```

**Comment by manjeetcars24** [comment]
The following seems to be working fine on 0.9.2

`            scrollRef?.current?.scrollTo?.({ x: 0, y: height / 2.5, animated: true });
`
