### ISSUE TITLE
New Bug in ancestor_check branch

### ISSUE THREAD

**Issue by cbcye** [APSL/react-native-keyboard-aware-scroll-view#55]
I use ancestor_check branch and modify the RN core file follow [Adds the ability to use UIManager to check if a node is an ancestor](https://github.com/facebook/react-native/commit/e52cab5a7f44aee5c145e9995850ab8051829b5c) , they seems working correct about Text input field component + Redux but **when just click a  input field  in a web page (WebView)  it occurred a error like below**.   my environment is  RN0.31 and NativeBase 0.52, NativeBase use the react-native-keyboard-aware-scroll-view as him Content component. Any one can give me some suggest?

Argument 0 (NSNumber) of RCTUIManager.viewIsDescendantOf must not be null

![wechatimg6](https://cloud.githubusercontent.com/assets/869074/17793738/2e50d5cc-65dc-11e6-975d-b770ecefb71b.jpeg)

**Comment by cbcye** [comment]
I add a line in lib/KeyboardAwareMixin.js after line:51 , I don't know is it correct, but it is not occur the error. Just it.
          
` if (this.props.enableAutoAutomaticScroll) {
            const currentlyFocusedField = TextInput.State.currentlyFocusedField();
            //disable focus if null, @Gary
            if (!currentlyFocusedField) return;
            UIManager.viewIsDescendantOf(
                currentlyFocusedField,
                this.getScrollHandle().getScrollResponder().getInnerViewNode(),
                (isAncestor) => {
                    if (isAncestor) {
                        this.scrollToFocusedInputWithNodeHandle(currentlyFocusedField)
                    }
                }
            )

        }`

**Comment by alvaromb** [comment]
Just added your suggestion @cbcye. Will finish testing with the new RN version and will release tomorrow the new keyboard aware version.

Thanks!
