### ISSUE TITLE
iOS broken  on 0.2.0

### ISSUE THREAD

**Issue by jasonfma** [APSL/react-native-keyboard-aware-scroll-view#59]
Upgraded to 0.2.0 (which fixes some scrolling issues on Android) but now iOS is broken

<img width="325" alt="screen shot 2016-08-25 at 10 03 00 pm" src="https://cloud.githubusercontent.com/assets/7075070/17994677/b6e9ea44-6b0f-11e6-9aa6-fab58c546cf0.png">

**Comment by alvaromb** [comment]
Please read the README file. React Native 0.32 is mandatory to use 0.2.0. 

Enviado desde mi iPhone

**Comment by jasonfma** [comment]
Ah right ok. Might be good to add it as a peerdependency. I'll see if I can find some time today for a PR. Thanks.
