### ISSUE TITLE
Some props of KeyboardAwareListView are not required

### ISSUE THREAD

**Issue by whs** [APSL/react-native-keyboard-aware-scroll-view#60]
KeyboardAwareListView inherited propTypes from ListView. Some of the props there are listed with `.isRequired` but do have default props set. As KeyboardAwareListView doesn't have default props, this would trigger some warnings in development mode.

**Comment by alvaromb** [comment]
Hi @whs!

What do you recommend to avoid the warnings?

**Comment by whs** [comment]
I think [this line](https://github.com/APSL/react-native-keyboard-aware-scroll-view/blob/master/lib/KeyboardAwareListView.js#L9) can be removed. If some of the ListView required props are missing it would complain using its own propTypes directly.
