### ISSUE TITLE
Android dismisses keyboard on scroll

### ISSUE THREAD

**Issue by chuckyouliu** [APSL/react-native-keyboard-aware-scroll-view#62]
Using the latest version on RN 0.32:

When focusing on a text input that requires scrolling, it'll correctly readjust the position of the text input to above the keyboard, but then dismisses the keyboard. Strangely, if you tap on the text input again, the keyboard will pop up, but then dismiss itself after entering a single character. Then focusing on that text input again will allow you to write whatever you'd like.

Issue only seen on Android. Has anyone else seen this behavior?

Edit: Looking at the mixin some more, it seems the latest release only works on iOS - the keyboard events are never triggered on Android, and would throw an error if they were for using UIManager. Is there something needed for Android to keep the keyboard up - maybe in the manifest file?

**Comment by chuckyouliu** [comment]
Looking at the mixin some more, it seems the latest release only works on iOS - the keyboard events are never triggered on Android, and would throw an error if they were for using UIManager. Is there something needed for Android to keep the keyboard up - maybe in the manifest file?

**Comment by renanlecaro** [comment]
Do you know about the keyboardshouldpersisttaps option on scrollViews ? 
https://facebook.github.io/react-native/docs/scrollview.html#keyboardshouldpersisttaps

**Comment by chuckyouliu** [comment]
Actually for me it seemed like the strange behavior was being caused by the keyboardDismissMode being set to on-drag. When the scrollview was being adjusted to the focused input, it would dismiss the keyboard as I guess it was being "dragged". I removed that and now it works as expected. I don't know if anyone else has seen this behavior.

Going to close this issue.
