### ISSUE TITLE
Don't allow user to scroll the view on static view

### ISSUE THREAD

**Issue by robcalcroft** [APSL/react-native-keyboard-aware-scroll-view#72]
I have a static view that I would usually just use `<View>` for, but I need the view to scroll to show some text inputs near the bottom of the window. Is there a way to stop the user dragging the view around ie. make the view act like a `<View>` but programmatically scroll as if it were a `<ScrollView>` as this makes it look odd when the view can be scrolled with no need for scrolling

**Comment by alvaromb** [comment]
Have you tried to disable the vertical bounce? Maybe that solves your issue!

Enviado desde mi iPhone

**Comment by robcalcroft** [comment]
I actually found `scrollEnabled={false}` works for me. Thanks for pointing me in the right direction though 😄
