### ISSUE TITLE
is there a way to use scrollTo with KeyboardAwareScrollView?

### ISSUE THREAD

**Issue by jsappme** [APSL/react-native-keyboard-aware-scroll-view#81]
I am not able to use scrollTo with KeyboardAwareScrollView. Am I missing something?

**Comment by alvaromb** [comment]
I don't know, can you show me teh code plz? 😉

**Comment by jsappme** [comment]
oops I did not see I can use resetScrollToCoords

**Comment by alvaromb** [comment]
👍
