### ISSUE TITLE
Dragging view "jitters" on iOS

### ISSUE THREAD

**Issue by coderdave** [APSL/react-native-keyboard-aware-scroll-view#88]
Has anyone experienced the view "jittering" when you drag it? It happens when using:
`<KeyboardAwareScrollView keyboardDismissMode='on-drag' keyboardShouldPersistTaps={true}>`

Also, it adds extra space at the top and bottom of the view?
Edit: Setting `automaticallyAdjustContentInsets={false}` removes the space at the top, not the bottom however.

**Comment by alvaromb** [comment]
The extra space may be due to the `ScrollView` automatically adjusting content insets.

**Comment by eHallberg** [comment]
I have the same issue, anyone got a solution?

This is my setup:
`
<KeyboardAwareScrollView extraScrollHeight={ 200 }
                    automaticallyAdjustContentInsets={ false }
                    keyboardDismissMode={ 'on-drag' }
                    keyboardShouldPersistTaps={ true }
                    automaticallyAdjustContentInsets={ false }
                    ref="scroll">
`

**Comment by alvaromb** [comment]
Can you upload a gif with the current behaviour? I'm not experiencing any "jittering" and I hardly believe it's because of this lib. I bet this is something related to the underlying `ScrollView`.

**Comment by alvaromb** [comment]
Can you post your full component source code and the RN version you're running on?

**Comment by eHallberg** [comment]
@alvaromb 
gist: https://gist.github.com/eHallberg/62383c6965b2469fe4b7c756d4ab1118

**Comment by alvaromb** [comment]
Thanks @eHallberg! Testing it right now.

**Comment by coderdave** [comment]
I'm using RN 0.39. If it sheds light on the problem, I'm using this gist for ios: https://gist.github.com/dbasedow/f5713763802e27fbde3fc57a600adcd3
then using this library for android.

**Comment by alvaromb** [comment]
This is definitely a problem with the upstream component `ScrollView` and the `'on-drag'` prop of `keyboardDismissMode`. I'm trying to understand why it's not appearing when using the `'interactive'` mode...

**Comment by alvaromb** [comment]
The "jittering" seems to be produced by resetting the scroll position when dismissing the keyboard. I'm trying to find a workaround.

**Comment by alvaromb** [comment]
In the meantime, can you guys use the `'interactive'` dismiss mode?

**Comment by eHallberg** [comment]
@alvaromb Yeah, ill do that meanwhile. Thx for the quick answers!

**Comment by hitbear518** [comment]
try set ```enableResetScrollToCoords``` to false,this works for me.
Besides, I think it should default to false if ```resetScrollToCoords``` is undefined

**Comment by mikaelengstrom** [comment]
I can confirm the @hitbear518 fix. Works fine for me to.

**Comment by alvaromb** [comment]
Can you test the new release? https://github.com/APSL/react-native-keyboard-aware-scroll-view/releases/tag/v0.4.2

Ping me if this issue still persists and I'll reopen.

Thanks.

**Comment by alelaru** [comment]
@alvaromb this is still an issue with the current version
