### ISSUE TITLE
After showing keyboard KeyboardAwareScrollView seems to compensate for the StatusBar

### ISSUE THREAD

**Issue by gkrinc** [APSL/react-native-keyboard-aware-scroll-view#91]
When I first load my scene whose render method looks like this:

```
render() {
  return (
    <KeyboardAwareScrollView style={{ backgroundColor: 'red' }}
                             keyboardShouldPersistTaps={true}
                             extraScrollHeight={170}>
      <View style={{ flex: 1 }}>
        ...
      </View>
    </KeyboardAwareScrollView>
  );
},
```

This is what the top of the app looks like:
![screen shot 2017-01-12 at 2 25 42 pm](https://cloud.githubusercontent.com/assets/2718382/21904856/16c74336-d8d3-11e6-9bc6-45db0a6c9b5f.png)
The component inside the KeyboardAwareScrollView has a background color of blue, therefore we are scrolled right to the top, because we can't see the red background color of the KeyboardAwareScrollView.

After focusing a TextField and showing the keyboard then hiding the keyboard and scrolling to the top of the scene this is what the top of the app looks like:
![screen shot 2017-01-12 at 2 26 02 pm](https://cloud.githubusercontent.com/assets/2718382/21904920/55660dd4-d8d3-11e6-87ca-3a9669d5d480.png)

It seems as though the KeyboardAwareScrollView is suddenly trying to compensate for the Status Bar?! What's weird in that when I use the inspector and select the KeyboardAwareScrollView/ScrollView they both show a width/height of 375x667 (iPhone6), no padding, no margins so I have no idea why when I'm scrolled to the top the KeyboardAwareScrollview it's showing part of it's background color the exact height of the Status Bar.

I'm using KeyboardAwareScrollView in other scenes in my app without experiencing this issue. Has anyone else run across this? Is it KeyboardAwareScrollView or something else within react-native?

**Versions**
* react-native: 0.37.0
* react-native-keyboard-aware-scroll-view: 0.2.4

**Comment by gkrinc** [comment]
Gah!! I always find the solution after taking the time to submit an issue :s

This problem is resolved using **automaticallyAdjustContentInsets={false}** like this

As per: https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/45#issuecomment-244439514

**Comment by jpokrzyk** [comment]
Whoa good timing. Just had the same issue/question. Glad this was documented here in the issues. This would have been a pain to track down in the react docs.

**Comment by sospedra** [comment]
You da real MVP 🙌
