### ISSUE TITLE
Use TouchableWithoutFeedback with KeyboardAwareScrollView on REact native 0.34

### ISSUE THREAD

**Issue by shrutic** [APSL/react-native-keyboard-aware-scroll-view#94]
I am trying to create a form with multiple text inputs enclosed by a KeyboardAwareScrollView. I also wanted the ability for users to dismiss keyboard if they tap anywhere other than inside the text inputs, hence using the TouchableWithoutFeedback.

My view layout 
<TouchableWithoutFeedback onPress="this.dismissKeyboard.bind(this)">
    <KeyboardAwareScrollView
                        keyboardShouldPersistTaps={true}
                        style={CustomEventStyleSheet.customEventCard}
      >
                <TextInput ....>
                <TextInput ....>
                <TextInput ....>
    </KeyboardAwareScrollView>
</TouchableWithoutFeedback>

With this setup, I am never able to get the this.dismissKeyboard associated with TouchableWithoutFeedback to be triggered. Could you let me know how I can use TouchableWithoutFeedback?

**Comment by alvaromb** [comment]
Hi!

Try setting the `ScrollView` `keyboardDismissMode` prop http://facebook.github.io/react-native/releases/next/docs/scrollview.html#keyboarddismissmode

**Comment by shrutic** [comment]
```
 <TouchableWithoutFeedback onPress={this.dismissKeyboard.bind(this)}>
             <KeyboardAwareScrollView
                style = {{flex: 1}}
                keyboardShouldPersistTaps={true}
                extraScrollHeight={60}
                extraHeight={20}
             >
                      <TextInput ....>
                     <TextInput ....>
                     <TextInput ....>
         </KeyboardAwareScrollView>
</TouchableWithoutFeedback>
```
Here the TouchableWithoutFeedback is a no-op. So I remove the TouchableWithoutFeedback and my new View layout is below:

 ```
         <KeyboardAwareScrollView
                style = {{flex: 1}}
                keyboardShouldPersistTaps={true}
                keyboardDismissMode='interactive'
                extraScrollHeight={60}
                extraHeight={20}
             >
                      <TextInput ....>
                     <TextInput ....>
                     <TextInput ....>
         </KeyboardAwareScrollView>
```
Now however, I get the following incorrect behavior:

- Tap on TextInput1 and the keyboard launches as usual
- Now tapping on TextInput2, causes the keyboard to dismiss, but does NOT cause the focus to change to TextInput2
- I now need to do a second tap to get the focus into the TextInput2

I am on React Native 0.34 version. 

Could you let me know how I can resolve this so that:

- I can dismiss the keyboard when I tap outside of the view
- Change focus in just one tap

Appreciate the help
