### ISSUE TITLE
Bounce on Focus (Disabling Animation)

### ISSUE THREAD

**Issue by indivisable** [APSL/react-native-keyboard-aware-scroll-view#95]
Is there anyway to disable the animation and directly jump to the focused input? When I use the nextKey to focus next input the animation jumps up and down.

I tried to change this in library with no luck:

![feb-01-2017 18-48-50](https://cloud.githubusercontent.com/assets/22860891/22532788/1f312cc6-e8af-11e6-9e43-fa580fb64ab9.gif)

```
  scrollToPosition: function (x: number, y: number, animated: bool = false) {
    const scrollView = this.refs._rnkasv_keyboardView.getScrollResponder()
    scrollView.scrollResponderScrollTo({x: x, y: y, animated: false}) // disable animation
  },
```

May be related to: https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/82

**Comment by alvaromb** [comment]
Have you tried to disable automatic scrolling? https://github.com/APSL/react-native-keyboard-aware-scroll-view#props

**Comment by indivisable** [comment]
@alvaromb Doesn't this defeat the purpose of using this library?

**Comment by alvaromb** [comment]
Well, I think I don't get exactly what you need, sorry!

Can you elaborate? Do you need to disable the automatic scroll or another thing?

**Comment by indivisable** [comment]
I shared a screencast above, when you use the Next key on keyboard it does this weird bounce up then down. I was wondering if there is a way to disable animation and just jump, I know ScrollView has the option to disable animated scroll and insta-jump to location.

**Comment by alvaromb** [comment]
Ok, this may be due to this other issue: https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/82

I'm sending a PR in a moment and it would be great if you could test it to check if it solves your issue.

**Comment by indivisable** [comment]
Sounds good @alvaromb thanks for the help 👍

**Comment by alvaromb** [comment]
Please use `v0.2.7` and test again your issue.

**Comment by indivisable** [comment]
@avallbona works perfect now, great work man!

**Comment by Pabloicaza** [comment]
For me was: automaticallyAdjustContentInsets={false}

**Comment by haddadnj** [comment]
I'm having this exact issue in v0.3.0. I'm on IOS as well.

**Comment by haddadnj** [comment]
I was able to fix this by adding blurOnSubmit={ false } to all of my inputs.

**Comment by luco** [comment]
@haddadnj It gives me a better result, but still bouncing a bit.
