### ISSUE TITLE
"this.scrollView.scrollTo is not a function"

### ISSUE THREAD

**Issue by shrutic** [APSL/react-native-keyboard-aware-scroll-view#98]
I created a reference to the KeyboardAwareScrollView and I am trying to scroll to the top of the scrollView when ever the keyboard is dismissed.  My goal is that irrespective of which TextInput I am on when keyboard is dismissed, I want the scrollView to scroll to the very top when keyboard is dismissed.

My View setup in typescript is below

<TouchableOpacity
      onPress={this.dismissKeyboard.bind(this)}
       activeOpacity={1}
 > 
          <KeyboardAwareScrollView
                automaticallyAdjustContentInsets={false}
                style={{flex: 1}}
                keyboardShouldPersistTaps={true}
                scrollEventThrottle={10}
                extraHeight={150}
                ref={this.setScrollView.bind(this)}
             >
                 <TouchableOpacity
                    onPress={this.dismissKeyboard.bind(this)}
                    activeOpacity={1}
                 >
                         <TextInput/>
                         <TextInput/>
                         <TextInput/>
                  </TouchableOpacity>
            </KeyboardAwareScrollView>
  </TouchableOpacity>

private dismissKeyboard() {
        this.scrollView.scrollTo({animated: true, x: 0, y: 0});
}
 
Whenever I dismiss keyboard I get a warning in Xcode(iOS) "Unhandled JS Exception: this.scrollView.scrollTo is not a function. (In 'this.scrollView.scrollTo({animated:true,x:0,y:0})', 'this.scrollView.scrollTo' is undefined)"

I thought we could use the react native's scrollView's functions with the KeyboardAwareScrollView. Could you please let me know how I can resolve this?
Appreciate the help

**Comment by shrutic** [comment]
Never mind .. Just found resetScrollToCoords to use . .Works like a charm,

**Comment by alvaromb** [comment]
Cool @shrutic !
